Repository ExpressionEngine/ExpressionEngine, pull requests merged in 2021-12, with the labels that each got.

#1119 Fix a bug with avatar filename in controller profile settings
  changelogs/patch.md
  system/ee/EllisLab/ExpressionEngine/Controller/Members/Profile/Settings.php
Labels: EE5

#1122 Fix bug with member import error
  changelogs/patch.md
  system/ee/EllisLab/ExpressionEngine/Controller/Utilities/MemberImport.php
Labels: EE5

#1174 Fix a bug with the importer converter filter
  changelogs/patch.md
  system/ee/EllisLab/ExpressionEngine/View/utilities/import/fieldmap.php
Labels: EE5

#1175 Fixed a bug with debug variables not being filtered
  changelogs/patch.md
  system/ee/EllisLab/ExpressionEngine/Service/Profiler/Section/Variables.php
Labels: EE5

#1553 Filter forum preview topic body
  system/ee/EllisLab/Addons/forum/mod.forum_core.php
Labels: EE5

#1500 Clean forum mail
  system/ee/EllisLab/Addons/member/mod.member_memberlist.php
Labels: EE5

#1225 Fixing comment bug for ee5
  system/ee/EllisLab/Addons/comment/mod.comment.php
Labels: EE5

#1223 forum closing update for 5
  system/ee/EllisLab/Addons/forum/mod.forum_core.php
  system/ee/templates/_themes/forum/blue/forum_announcements/announcement.html
  system/ee/templates/_themes/forum/blue/forum_threads/thread_rows.html
  system/ee/templates/_themes/forum/default/forum_announcements/announcement.html
  system/ee/templates/_themes/forum/default/forum_threads/thread_rows.html
  system/ee/templates/_themes/forum/developer/forum_announcements/announcement.html
  system/ee/templates/_themes/forum/developer/forum_threads/thread_rows.html
  system/ee/templates/_themes/forum/grey/forum_announcements/announcement.html
  system/ee/templates/_themes/forum/grey/forum_threads/thread_rows.html
  system/ee/templates/_themes/forum/shares/forum_announcements/announcement.html
  system/ee/templates/_themes/forum/shares/forum_threads/thread_rows.html
Labels: EE5

#1176 Fixed a bug with the error message when importing invalid channel sets
  changelogs/patch.md
  system/ee/EllisLab/ExpressionEngine/Controller/Channels/Sets.php
  system/ee/legacy/language/english/channel_lang.php
Labels: EE5

#1498 Clean up forum messages
  system/ee/legacy/libraries/Messages_send.php
Labels: EE5

#1340 Allow assign previously created field groups to importing channel sets
  changelogs/minor.md
  system/ee/ExpressionEngine/Service/ChannelSet/Set.php
Labels: enhancement: accepted, community feature

#1629 Bug/5.dev/clean member import
  system/ee/EllisLab/ExpressionEngine/Controller/Utilities/MemberImport.php
  system/ee/EllisLab/ExpressionEngine/Library/Security/XSS.php
  system/ee/EllisLab/Tests/ExpressionEngine/Library/Security/XSSTest.php
Labels: EE5

#1637 Escape the key in search query
  system/ee/EllisLab/Addons/member/mod.member_settings.php
Labels: EE5

#1640 Remove name from email templates
  system/ee/legacy/language/english/email_data.php
Labels: EE5

#1636 Bug/6.dev/clean member mini search
  system/ee/ExpressionEngine/Addons/member/mod.member_settings.php
Labels: EE6

#1635 Clean edit entry modal
  system/ee/ExpressionEngine/View/publish/live-preview-modal.php
Labels: EE6

#1639 Remove name from email templates
  system/ee/language/english/email_data.php
Labels: EE6

#1634 Bug/6.dev/clean member import
  system/ee/ExpressionEngine/Addons/forum/mod.forum_core.php
  system/ee/ExpressionEngine/Controller/Channels/Channels.php
  system/ee/ExpressionEngine/Controller/Utilities/MemberImport.php
  system/ee/ExpressionEngine/Library/Security/XSS.php
  system/ee/ExpressionEngine/Tests/ExpressionEngine/Library/Security/XSSTest.php
Labels: EE6

#1661 Bug/6.2.0/fix cli updater
  system/ee/ExpressionEngine/Cli/Cli.php
  system/ee/ExpressionEngine/Cli/Commands/CommandUpdate.php
  system/ee/installer/controllers/wizard.php
  system/ee/installer/updater/ExpressionEngine/Updater/Service/Updater/Runner.php
  system/ee/installer/updates/ud_6_02_00.php
  system/ee/legacy/core/Config.php
Labels: EE6
