Repository ExpressionEngine/ExpressionEngine, pull requests merged in 2022-10, with the labels that each got.

#2342 Added "Upload Directory" column for File Manager table; #98
  system/ee/ExpressionEngine/Library/CP/FileManager/ColumnFactory.php
  system/ee/ExpressionEngine/Library/CP/FileManager/Columns/UploadDirectory.php
Labels: enhancement

#2345 Enabled entering HTML line break tags into Entry Title fiels; #1633
  system/ee/ExpressionEngine/Model/Channel/ChannelEntry.php
  system/ee/legacy/libraries/Typography.php
Labels: enhancement

#2354 Show in which channels field is used on field edit page; #919
  system/ee/ExpressionEngine/Controller/Fields/Fields.php
  system/ee/language/english/admin_content_lang.php
Labels: enhancement: accepted

#2358 Added visual indication when viewing entry version; #1897
  system/ee/ExpressionEngine/Controller/Publish/Edit.php
  system/ee/ExpressionEngine/View/publish/partials/publish_form.php
  system/ee/ExpressionEngine/View/publish/partials/revision_badge.php
  system/ee/language/english/content_lang.php
Labels: enhancement: accepted

#2378 Added extra confirmation toggle when deleting fieldtype that is used by fields; #484
  system/ee/ExpressionEngine/Controller/Addons/Addons.php
  system/ee/ExpressionEngine/View/_shared/add-on-card.php
  system/ee/language/english/addons_lang.php
  system/ee/language/english/cp_lang.php
  system/ee/language/english/filemanager_lang.php
  system/ee/legacy/libraries/Core.php
  system/ee/legacy/libraries/Cp.php
  themes/ee/cp/js/build/cp/add-ons.js
  themes/ee/cp/js/src/cp/add-ons.js
Labels: enhancement

#1841 Resolved #1541 where some fields connected to toggle button were not showing or hiding accordingly
  build-tools/build.json
  system/ee/ExpressionEngine/Tests/bootstrap.php
  system/ee/installer/controllers/wizard.php
  system/ee/installer/updates/ud_6_04_00.php
  system/ee/legacy/libraries/Core.php
  tests/cypress/support/config/config.php
  themes/ee/asset/javascript/src/common.js
Labels: Bug: Accepted

#2235 Resolved #2128 where settings of Checkboxes column in Grid field were not saved
  themes/ee/asset/javascript/src/cp/grid.js
Labels: Bug: Accepted

#2328 Resolved #2121 where hitting esc in New Entry slideout modal could case data loss
  themes/ee/asset/javascript/src/cp/modal_form.js
Labels: Bug: Accepted

#1668 Use original filename of uploaded files as fallback for title; #1660
  system/ee/ExpressionEngine/Service/File/Upload.php
  system/ee/legacy/models/file_model.php
  tests/cypress/cypress/integration/files/upload_file.ee6.js
Labels: enhancement: accepted

#2290 Resolved #2131, #913 where moving fields between tabs in Channel Layouts did not work well
  cp-styles/app/styles/components/_layout-item.scss
  cp-styles/app/styles/legacy/_tabs.scss
  themes/ee/asset/javascript/src/cp/channel/layout.js
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#1902 Added possibility to defer initialization of Relationship field
  system/ee/ExpressionEngine/Addons/relationship/ft.relationship.php
  system/ee/ExpressionEngine/Addons/relationship/views/publish.php
  system/ee/language/english/fieldtypes_lang.php
  tests/cypress/cypress/integration/publish/relationship.ee6.js
  themes/ee/cp/js/build/components/relationship.js
  themes/ee/cp/js/src/components/relationship.jsx
Labels: community feature, performance

#2434 Resolved #2430 where editing template by member without settings & access permission was resetting allowed roles
  system/ee/ExpressionEngine/Controller/Design/Template.php
Labels: Bug: Accepted

#2433 Resolved #2430 where editing template by member without settings & access permission was resetting allowed roles
  system/ee/ExpressionEngine/Controller/Design/Template.php
Labels: Bug: Accepted

#2440 Resolved #2431 where Image HTML button should not have been editable
  cp-styles/app/styles/base/_inputs.scss
  cp-styles/pages/entry.php
  system/ee/ExpressionEngine/Config/html_buttons.php
  system/ee/ExpressionEngine/Controller/Settings/Buttons.php
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#2441 Resolved #2431 where Image HTML button should not have been editable
  cp-styles/app/styles/base/_inputs.scss
  cp-styles/pages/entry.php
  system/ee/ExpressionEngine/Config/html_buttons.php
  system/ee/ExpressionEngine/Controller/Settings/Buttons.php
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#2305 Resolved #2298 where Publish Layouts were not accessible for member via secondary role
  system/ee/ExpressionEngine/Controller/Publish/Edit.php
  system/ee/ExpressionEngine/Controller/Publish/Publish.php
Labels: Bug: Accepted

#2283 Resolved #2122 where Live Preview was not working correctly when template was using search on checkboxes column in Grid
  system/ee/legacy/models/grid_model.php
Labels: Bug: Accepted

#2237 Resolved #2126 where "add field" button was present for field groups that are not saved yet
  system/ee/ExpressionEngine/Controller/Fields/Groups.php
Labels: Bug: Accepted

#2429 Namespaced the Structure core nav parser to avoid conflicts with the …
  system/ee/ExpressionEngine/Addons/structure/libraries/Structure_nav_parser.php
  system/ee/ExpressionEngine/Addons/structure/mod.structure.php
Labels: Bug: Accepted

#622 Fixing broken link, and altering some of the wording
  .github/ISSUE_TEMPLATE/4-i-need-help.md
Labels: EE5

#2100 Emit more events on model association manipulations
  system/ee/ExpressionEngine/Service/Model/Model.php
  system/ee/ExpressionEngine/Service/Model/Query/Delete.php
Labels: development

#1983 Added indicator to display number of installed add-ons, #1944
  cp-styles/app/styles/components/_tab-bar.scss
  cp-styles/app/styles/themes/_theme-dark-default.scss
  cp-styles/app/styles/themes/_theme-light-default.scss
  system/ee/ExpressionEngine/View/addons/index.php
  themes/ee/cp/css/common.min.css
  themes/ee/debug/css/eecms-debug.min.css
Labels: enhancement: accepted

#2088 Resolved issue where notices could be shown by Template library when called by add-on in PHP 8.1
  system/ee/legacy/libraries/Template.php
Labels: Bug: Accepted

#2323 Resolved #2116 where disabling MFA globally could cause redirect loop on login for some users
  system/ee/legacy/controllers/cp/login.php
  system/ee/legacy/libraries/Core.php
Labels: Bug: Accepted

#2367 Feature/6.x/object addons
  system/ee/ExpressionEngine/Controller/Addons/Addons.php
  system/ee/ExpressionEngine/Library/String/Str.php
  system/ee/ExpressionEngine/Service/Addon/Addon.php
  system/ee/ExpressionEngine/Service/Addon/Controllers/AbstractRoute.php
  system/ee/ExpressionEngine/Service/Addon/Controllers/Action/AbstractRoute.php
  system/ee/ExpressionEngine/Service/Addon/Controllers/Controller.php
  system/ee/ExpressionEngine/Service/Addon/Controllers/Extension/AbstractRoute.php
  system/ee/ExpressionEngine/Service/Addon/Controllers/Mcp/AbstractRoute.php
  system/ee/ExpressionEngine/Service/Addon/Controllers/Tag/AbstractRoute.php
  system/ee/ExpressionEngine/Service/Addon/Exceptions/ControllerException.php
  system/ee/ExpressionEngine/Service/Addon/Exceptions/Controllers/Mcp/RouteException.php
  system/ee/ExpressionEngine/Service/Addon/Exceptions/Controllers/RouteException.php
  system/ee/ExpressionEngine/Service/Addon/Extension.php
  system/ee/ExpressionEngine/Service/Addon/Mcp.php
  system/ee/ExpressionEngine/Service/Addon/Module.php
  system/ee/ExpressionEngine/Tests/ExpressionEngine/Service/Addon/Controllers/ControllerTest.php
  system/ee/ExpressionEngine/Tests/ExpressionEngine/Service/Addon/McpTest.php
  system/ee/ExpressionEngine/Tests/ExpressionEngine/Service/Addon/ModuleTest.php
  system/ee/ExpressionEngine/Tests/phpunit.xml
Labels: enhancement: accepted
