Repository ExpressionEngine/ExpressionEngine, pull requests merged in 2022-08, with the labels that each got.

#2209 Resolved #2208 where language files were for some add-ons were not placed in correct location
  system/ee/ExpressionEngine/Addons/moblog/language/english/moblog_lang.php
  system/ee/ExpressionEngine/Addons/pro/Controller/Authenticate/Authenticate.php
  system/ee/ExpressionEngine/Addons/pro/Controller/Logs/Consent.php
  system/ee/ExpressionEngine/Addons/pro/Controller/Members/Profile/Mfa.php
  system/ee/ExpressionEngine/Addons/pro/Controller/Prolet/Prolet.php
  system/ee/ExpressionEngine/Addons/pro/Service/Access/Access.php
  system/ee/ExpressionEngine/Addons/pro/Service/Dock/DockFactory.php
  system/ee/ExpressionEngine/Addons/pro/Service/Mfa/Mfa.php
  system/ee/ExpressionEngine/Addons/pro/mcp.pro.php
  system/ee/ExpressionEngine/Addons/pro/mod.pro.php
  system/ee/ExpressionEngine/Controller/Design/Template.php
  system/ee/ExpressionEngine/Controller/Fields/Fields.php
  system/ee/ExpressionEngine/Controller/Logs/Consent.php
  system/ee/ExpressionEngine/Controller/Members/Profile/Profile.php
  system/ee/ExpressionEngine/Controller/Members/Roles/Roles.php
  system/ee/ExpressionEngine/Controller/Settings/Settings.php
  system/ee/ExpressionEngine/Core/Provider.php
  system/ee/ExpressionEngine/Service/JumpMenu/JumpMenu.php
  system/ee/language/english/moblog_lang.php
  system/ee/language/english/pro_lang.php
  system/ee/legacy/controllers/cp/login.php
  system/ee/legacy/libraries/Core.php
Labels: Bug: Accepted

#2261 Resolved #2228 where dropdown to create entry inside Relationship field was not positioned properly
  themes/ee/cp/js/build/components/relationship.js
  themes/ee/cp/js/src/components/relationship.jsx
Labels: Bug: Accepted

#2254 Resolved #2103 where value column of conditional field settings could be populated with wrong values
  themes/ee/asset/javascript/src/cp/conditional_logic.js
Labels: Bug: Accepted

#2252 Resolved #2248 where emphasized markdown was placed in separate line inside Notes field
  cp-styles/app/styles/components/_note-field.scss
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#2246 Resolved issue where PHP notice could be shown when calling Template library from an add-on
  system/ee/legacy/libraries/Template.php
Labels: development

#2239 Resolved #2136 where formatters for duration field set to hours type were not parsed properly
  system/ee/ExpressionEngine/Addons/duration/Traits/DurationTrait.php
Labels: Bug: Accepted

#2253 Resolved #2103 where value column of conditional field settings could be populated with wrong values
  themes/ee/asset/javascript/src/cp/conditional_logic.js
Labels: Bug: Accepted

#2251 Resolved #2248 where emphasized markdown was placed in separate line inside Notes field
  cp-styles/app/styles/components/_note-field.scss
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#2120 Resolved issue when PHP error was shown for non-existing addons
  system/ee/ExpressionEngine/Controller/Addons/Addons.php
Labels: Bug: Accepted

#2119 Resolved issue when SQL error was shown in Channel Form when field limits by member group instead of role
  system/ee/ExpressionEngine/Addons/channel/libraries/channel_form/Channel_form_lib.php
Labels: Bug: Accepted

#2083 Resolved issue where MetaWeblog could not post if `channel_id` is not available
  system/ee/ExpressionEngine/Addons/metaweblog_api/mod.metaweblog_api.php
Labels: Bug: Accepted

#2061 Improved UI for category pages
  cp-styles/app/styles/components/_fieldsets.scss
  themes/ee/cp/css/common.min.css
Labels: enhancement: accepted

#1976 Resolved #1561 where file column in file grid field was not searchable
  system/ee/ExpressionEngine/Addons/grid/ft.file_grid.php
Labels: Bug: Accepted

#2097 Added support for table alias in SQL joins when using Active Record, #2096
  system/ee/legacy/database/DB_active_rec.php
Labels: enhancement: accepted

#2218 Resolved issue when PHP error was shown for non-existing addons
  system/ee/ExpressionEngine/Controller/Addons/Addons.php
Labels: Bug: Accepted

#2211 Resolved #1561 where file column in file grid field was not searchable
  system/ee/ExpressionEngine/Addons/grid/ft.file_grid.php
Labels: Bug: Accepted

#2094 Improved UI for category pages
  system/ee/ExpressionEngine/View/channels/layout/index.php
Labels: enhancement: accepted

#2124 Resolved #2090 where page leaving warning was displayed when switching upload directory in modal
  cp-styles/app/styles/base/_table.scss
  themes/ee/asset/javascript/src/cp/publish/publish.js
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#2210 Added indicator to display number of installed add-ons, #1944
  cp-styles/app/styles/components/_tab-bar.scss
  cp-styles/app/styles/themes/_theme-light-pink.scss
  cp-styles/app/styles/themes/_theme-light-snow.scss
  system/ee/ExpressionEngine/View/addons/index.php
  themes/ee/cp/css/common.min.css
  themes/ee/debug/css/eecms-debug.min.css
Labels: enhancement: accepted

#2216 Improved UI for category pages
  cp-styles/app/styles/components/_checkboxes-and-radios.scss
  cp-styles/app/styles/components/_fieldsets.scss
  system/ee/ExpressionEngine/Controller/Categories/Groups.php
  system/ee/ExpressionEngine/View/channels/layout/index.php
  themes/ee/cp/css/common.min.css
Labels: enhancement: accepted

#2214 Improved UI for field assignment
  system/ee/ExpressionEngine/Controller/Channels/Channels.php
  system/ee/ExpressionEngine/Controller/Fields/Groups.php
Labels: Bug: Accepted

#2215 Improved UI for editing system message templates
  cp-styles/app/styles/legacy/_legacy.scss
  system/ee/ExpressionEngine/Controller/Design/System.php
  system/ee/ExpressionEngine/View/design/system/edit.php
  system/ee/ExpressionEngine/View/design/system/index.php
  themes/ee/cp/css/common.min.css
Labels: enhancement: accepted

#2066 Enable `exp:search:total_results` to be parsed as tag pair, #1193
  system/ee/ExpressionEngine/Addons/search/mod.search.php
  tests/cypress/cypress/integration/addons/search.ee6.js
  tests/cypress/support/templates/default_site/search.group/index.html
  tests/cypress/support/templates/default_site/search.group/no_result.html
  tests/cypress/support/templates/default_site/search.group/simple_form.html
  tests/cypress/support/templates/search.group/no_result.html
Labels: enhancement: accepted

#2265 Resolved #2063 where outdated resources could be served
  system/ee/ExpressionEngine/Library/Resource/Request.php
  system/ee/legacy/libraries/Template.php
  tests/cypress/cypress/integration/design/template_of_resources.ee6.js
  tests/cypress/support/templates/default_site/resources.group/index.html
Labels: Bug: Accepted

#2270 Resolved issue when sometimes avatar could not be uploaded on frontend
  system/ee/legacy/libraries/Filemanager.php
Labels: Bug: Accepted

#2133 Resolved issue when sometimes avatar could not be uploaded on frontend
  system/ee/legacy/libraries/Filemanager.php
Labels: Bug: Accepted

#2273 Enable exp:search:total_results to be parsed as tag pair, #1193
  system/ee/ExpressionEngine/Addons/search/mod.search.php
  tests/cypress/cypress/integration/addons/search.ee6.js
  tests/cypress/support/templates/default_site/search.group/index.html
  tests/cypress/support/templates/default_site/search.group/no_result.html
  tests/cypress/support/templates/default_site/search.group/simple_form.html
  tests/cypress/support/templates/search.group/no_result.html
Labels: enhancement: accepted

#2274 Added has_children variable to category tags, #1726
  system/ee/ExpressionEngine/Addons/channel/mod.channel.php
  tests/cypress/cypress/integration/channel/categories.ee6.js
  tests/cypress/support/templates/default_site/cats.group/archive-nested.html
  tests/cypress/support/templates/default_site/cats.group/archive.html
Labels: enhancement: accepted

#2266 Resolved issue where MetaWeblog could not post if channel_id is not available
  system/ee/ExpressionEngine/Addons/metaweblog_api/mod.metaweblog_api.php
Labels: Bug: Accepted

#2243 Resolved #2105 where adding new row for File Grid inside Fluid could cause validation error
  system/ee/ExpressionEngine/Addons/file/ft.file.php
Labels: Bug: Accepted

#2247 Added support for table alias in SQL joins when using Active Record, #2096
  system/ee/legacy/database/DB_active_rec.php
Labels: development

#2268 Resolved #1358 where setting CP Homepage for member could cause PHP error on large sites using MSM
  system/ee/installer/schema/mysql_schema.php
  system/ee/installer/updates/ud_7_01_00.php
Labels: Bug: Accepted

#2314 Resolved #2297 where deferring relationship field was not working for fields with data
  themes/ee/cp/js/build/components/relationship.js
  themes/ee/cp/js/src/components/relationship.jsx
Labels: Bug: Accepted

#2259 Resolved #2255 where "Anonymize Consent Logs" feature was not fully functional
  system/ee/ExpressionEngine/Controller/Settings/Logging.php
  system/ee/ExpressionEngine/Model/Consent/Consent.php
  system/ee/legacy/core/Config.php
Labels: Bug: Accepted

#2152 Handle form_class in form_declaration tag within legacy forgot_form members template
  system/ee/ExpressionEngine/Addons/member/mod.member_auth.php
Labels: enhancement: accepted

#2271 Resolved #1901 where add-ons with related models were not properly uninstalled
  system/ee/legacy/libraries/addons/Addons_installer.php
Labels: Bug: Accepted

#2245 Resolved #2076, #2141 where button to update template routes was missing some functionality
  system/ee/ExpressionEngine/Controller/Design/Routes.php
  system/ee/ExpressionEngine/View/design/routes/index.php
Labels: Bug: Accepted

#2236 Resolved #2126 where "add field" button was present for field groups that are not saved yet
  system/ee/ExpressionEngine/Controller/Fields/Groups.php
Labels: Bug: Accepted

#2300 Resolved issue when member role record was not deleted after deleting member
  build-tools/build.json
  system/ee/ExpressionEngine/Addons/pro/Service/Access/Access.php
  system/ee/ExpressionEngine/Service/Model/Query/Delete.php
  system/ee/ExpressionEngine/Tests/bootstrap.php
  system/ee/installer/controllers/wizard.php
  system/ee/installer/updates/ud_7_01_02.php
  system/ee/legacy/libraries/Core.php
  tests/cypress/support/config/config.php
Labels: Bug: Accepted

#2108 Added extension hook to be executed upon cache clearing, #1762
  system/ee/legacy/libraries/Functions.php
Labels: enhancement: accepted

#2341 Pro Variables fixes
  cp-styles/app/styles/components/_add-on-overrides.scss
  cp-styles/app/styles/components/_grid-field.scss
  system/ee/ExpressionEngine/Addons/pro_variables/mod.pro_variables.php
  system/ee/ExpressionEngine/Addons/pro_variables/types/pro_grid/vt.pro_grid.php
  system/ee/ExpressionEngine/Addons/pro_variables/upd.pro_variables.php
  system/ee/ExpressionEngine/Addons/pro_variables/views/list.php
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#2336 Resolved #2335 where having references to non-existing files in File field could case PHP error in Entry Manager listing
  system/ee/ExpressionEngine/Addons/file/ft.file.php
  system/ee/legacy/libraries/File_field.php
Labels: Bug: Accepted
