Repository ExpressionEngine/ExpressionEngine, pull requests merged in 2022-01, with the labels that each got.

#1680 Fix bug with login page redirections
  system/ee/legacy/controllers/cp/login.php
  system/ee/legacy/libraries/Core.php
  tests/cypress/cypress/integration/cp/login.ee6.js
Labels: Bug: Accepted, EE6

#1103 Display the entry_id along with the channel name in Relationship fields
  changelogs/minor.md
  cp-styles/app/styles/components/_dropdown.scss
  cp-styles/app/styles/components/_list-group.scss
  system/ee/ExpressionEngine/Addons/relationship/ft.relationship.php
  system/ee/ExpressionEngine/Addons/relationship/libraries/EntryList.php
  system/ee/ExpressionEngine/Addons/relationship/views/publish.php
  system/ee/language/english/fieldtypes_lang.php
  tests/cypress/cypress/integration/publish/edit.ee6.js
  tests/cypress/cypress/integration/publish/relationship.ee6.js
  themes/ee/asset/javascript/src/common.js
  themes/ee/asset/javascript/src/components/select_list.es6
  themes/ee/asset/javascript/src/components/select_list.js
  themes/ee/asset/javascript/src/cp/form_group.js
  themes/ee/asset/javascript/src/fields/rte/redactor/redactor.min.js
  themes/ee/asset/javascript/src/fields/rte/redactor/redactor.min.js.map
  themes/ee/cp/css/common.min.css
  themes/ee/cp/js/build/components/relationship.js
  themes/ee/cp/js/src/components/relationship.jsx
Labels: EE6

#1713 Add cli enabled setting to jump menu
  system/ee/ExpressionEngine/Service/JumpMenu/JumpMenu.php
  system/ee/language/english/settings_lang.php
Labels: Bug: Accepted

#1710 Bug/6.dev/update cache clear for php81
  system/ee/legacy/helpers/file_helper.php
Labels: Bug: Accepted

#1719 Bug/6.dev/fix error in template post parse hook
  build-tools/build.json
  system/ee/ExpressionEngine/Cli/Commands/Upgrade/UpgradeMap.php
  system/ee/ExpressionEngine/Tests/bootstrap.php
  system/ee/installer/controllers/wizard.php
  system/ee/installer/updates/ud_6_02_01.php
  system/ee/legacy/libraries/Core.php
  system/ee/legacy/libraries/Template.php
  tests/cypress/support/config/config.php
Labels: Bug: Accepted
