Repository ExpressionEngine/ExpressionEngine, pull requests merged in 2023-05, with the labels that each got.

#3263 Added more information to template debugger when using `search` parameter in `exp:channel:entries`; #2670
  system/ee/ExpressionEngine/Addons/channel/mod.channel.php
Labels: enhancement

#3215 Improve string-to-boolean conversion; #1959
  system/ee/ExpressionEngine/Boot/boot.common.php
Labels: development

#3118 Added separate list with selected categories for Entry page Category tab #2807
  cp-styles/app/styles/components/_checkboxes-and-radios.scss
  system/ee/ExpressionEngine/Addons/checkboxes/ft.checkboxes.php
  system/ee/ExpressionEngine/Controller/Publish/AbstractPublish.php
  system/ee/ExpressionEngine/Model/Category/CategoryGroup.php
  system/ee/ExpressionEngine/View/_shared/form/fields/select.php
  system/ee/language/english/content_lang.php
  themes/ee/asset/javascript/src/components/select_list.es6
  themes/ee/asset/javascript/src/components/select_list.js
  themes/ee/cp/css/common.min.css
Labels: enhancement

#3300 Resolved #2387 where PHP error could be shown when several developer logs are existing
  system/ee/ExpressionEngine/Service/Alert/AlertCollection.php
Labels: Bug: Accepted

#3307 Resolved #2112 where deleting too many logs could cause the system go out of memory
  system/ee/ExpressionEngine/Controller/Logs/Logs.php
Labels: Bug: Accepted

#3309 Resolved #2843 where Channel Form was saving file field data in old format
  system/ee/legacy/libraries/File_field.php
Labels: Bug: Accepted

#3221 Resolved #2570 where saving empty "Select Entries" Pro Variable was throwing SQL error
  system/ee/ExpressionEngine/Addons/pro_variables/mcp.pro_variables.php
Labels: Bug: Accepted

#2818 Resolved #2609 where the permissions for Guests role could be incorrect and Guest could log in
  system/ee/ExpressionEngine/Controller/Members/Roles/Roles.php
  system/ee/legacy/libraries/Auth.php
  tests/cypress/cypress/integration/member_roles/member_roles_default.ee6.js
Labels: Bug: Accepted

#3236 Resolved #3224 where descending sorting order did not persist when using pagination in File Manager
  system/ee/ExpressionEngine/Library/CP/FileManager/Traits/FileManagerTrait.php
  tests/cypress/cypress/integration/files/file_manager.ee6.js
Labels: Bug: Accepted

#3223 Enabled File field to be used as Pro Variable; #2498
  system/ee/ExpressionEngine/Addons/file/ft.file.php
  system/ee/ExpressionEngine/Addons/pro_variables/mcp.pro_variables.php
  system/ee/language/english/pro_variables_lang.php
  system/ee/legacy/libraries/Cp.php
Labels: enhancement

#3324 Resolved issue where icons on Channels page were not self-evident
  system/ee/ExpressionEngine/Controller/Channels/Channels.php
Labels: enhancement

#3325 Resolved issue where setting member field type might not work properly when called programmatically
  system/ee/ExpressionEngine/Model/Member/MemberField.php
Labels: Bug: Accepted

#3345 Resolved #1795 Where display of negative numerical field has - placed incorrectly for RTL text direction
  cp-styles/app/styles/base/_inputs.scss
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#3336 Resolved #758 where installation wizard did not work when PHP was configured to have no memory limit
  system/ee/installer/updater/ExpressionEngine/Updater/Service/Updater/RequirementsChecker.php
Labels: Bug: Accepted

#3335 Resolved #3331 Where Categories tab shows empty alert when no category groups assigned
  cp-styles/app/styles/components/_alerts.scss
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#3334 Resolved status issues (see description)
  system/ee/ExpressionEngine/Controller/Publish/Edit.php
  system/ee/ExpressionEngine/Model/Channel/ChannelEntry.php
  system/ee/ExpressionEngine/Model/Channel/Display/DefaultChannelLayout.php
  system/ee/ExpressionEngine/Model/Content/Display/FieldDisplay.php
  system/ee/ExpressionEngine/Model/Content/Display/LayoutTab.php
  system/ee/ExpressionEngine/Model/Status/Status.php
  system/ee/language/english/content_lang.php
Labels: Bug: Accepted

#3332 Added extra information on RTE advanced configuration
  system/ee/language/english/rte_lang.php
Labels: enhancement: accepted

#3271 Resolved #3261 where empty Grid row could have been added in Fluid upon saving
  system/ee/ExpressionEngine/View/_shared/form/fields/dropdown.php
  themes/ee/asset/javascript/src/fields/dropdown/dropdown.es6
  themes/ee/asset/javascript/src/fields/dropdown/dropdown.js
Labels: Bug: Accepted

#3327 Added relationships to model definitions that were missing
  system/ee/ExpressionEngine/Addons/pro/Model/Dashboard/DashboardLayout.php
  system/ee/ExpressionEngine/Model/Category/Category.php
  system/ee/ExpressionEngine/Model/Category/CategoryField.php
  system/ee/ExpressionEngine/Model/Category/CategoryGroup.php
  system/ee/ExpressionEngine/Model/Channel/ChannelField.php
  system/ee/ExpressionEngine/Model/Channel/ChannelFieldGroup.php
  system/ee/ExpressionEngine/Model/Channel/ChannelLayout.php
  system/ee/ExpressionEngine/Model/File/FileDimension.php
  system/ee/ExpressionEngine/Model/Site/Site.php
  system/ee/ExpressionEngine/Model/Status/Status.php
Labels: development

#3329 Added `GridColumn` model
  system/ee/ExpressionEngine/Addons/grid/Model/GridColumn.php
  system/ee/ExpressionEngine/Addons/grid/addon.setup.php
  system/ee/ExpressionEngine/Model/Channel/ChannelField.php
  system/ee/legacy/models/grid_model.php
Labels: development

#3343 Wrap Structure global functions to avoid conflict
  system/ee/ExpressionEngine/Addons/structure/helper.php
Labels: Bug: Accepted

#3326 Improved counting members on role
  system/ee/ExpressionEngine/Model/Role/Role.php
Labels: enhancement: accepted

#3153 Raise required MySQL version to 5.6.4 in order to support InnoDB engine for Pro Search indexes
  system/ee/ExpressionEngine/Addons/pro_search/models/pro_search_index_model.php
  system/ee/installer/updater/ExpressionEngine/Updater/Service/Updater/RequirementsChecker.php
Labels: Bug: Accepted

#3269 Added `core_cp_boot` extension hook; #1557
  system/ee/ExpressionEngine/Service/Generator/Enums/Hooks.php
  system/ee/legacy/core/Controller.php
Labels: development

#3189 Added visual status indicator to Relationship field; #2522
  cp-styles/app/styles/components/_list-group.scss
  system/ee/ExpressionEngine/Addons/relationship/ft.relationship.php
  system/ee/ExpressionEngine/Addons/relationship/libraries/EntryList.php
  themes/ee/cp/css/common.min.css
  themes/ee/cp/js/build/components/relationship.js
  themes/ee/cp/js/src/components/relationship.jsx
Labels: enhancement

#3426 Resolved #3425 File:query deprecation notice in PHP 8.2
  system/ee/ExpressionEngine/Addons/file/mod.file.php
Labels: Bug: Accepted

#3406 Resolved #3402 where PHP 8.1 deprecation noticed were shown when bulk editing entries without Pages URL set but Pages module installed
  system/ee/ExpressionEngine/Addons/pages/tab.pages.php
Labels: Bug: Accepted

#3400 Resolved #3397 where Template Routes page was showing deprecation notices when using PHP 8.2
  system/ee/legacy/libraries/template_router/Converters.php
  system/ee/legacy/libraries/template_router/Part.php
  system/ee/legacy/libraries/template_router/Route.php
  system/ee/legacy/libraries/template_router/converters/Max_length.php
  system/ee/legacy/libraries/template_router/converters/Min_length.php
  system/ee/legacy/libraries/template_router/converters/Regex.php
Labels: Bug: Accepted

#3398 Resolved #3123 where having template records without template group in database would case PHP notices in template editor
  system/ee/ExpressionEngine/Controller/Design/Template.php
Labels: Bug: Accepted

#3374 Resolved #3371 where Grid fields could show PHP error when ExpressionEngine was updated from older version
  system/ee/ExpressionEngine/Addons/grid/ft.grid.php
Labels: Bug: Accepted

#3361 Resolved #3350 where PHP notice might be shown when parsing empty member field
  system/ee/ExpressionEngine/Model/Content/FieldModel.php
Labels: Bug: Accepted

#3473 Added right and left padding to error box
  cp-styles/app/styles/components/_fieldsets.scss
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted
