Repository ExpressionEngine/ExpressionEngine, pull requests merged in 2023-06, with the labels that each got.

#3491 Added image dimensions to modifier output
  system/ee/ExpressionEngine/Addons/file/ft.file.php
Labels: enhancement

#3416 Resolved #3259 where certain coditionals in templates could generate PHP warning
  system/ee/ExpressionEngine/Library/Parser/Conditional/BooleanExpression.php
Labels: Bug: Accepted

#3465 Resolved issue where it was impossible to edit Categories when using phone
  cp-styles/app/styles/components/_sidebar.scss
  cp-styles/app/styles/layout/_sidebar.scss
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#3502 Resolved issue where Fluid field from older ExpressionEngine versions did not display the data in CP
  build-tools/build.json
  system/ee/ExpressionEngine/Addons/fluid_field/ft.fluid_field.php
  system/ee/ExpressionEngine/Tests/bootstrap.php
  system/ee/installer/controllers/wizard.php
  system/ee/installer/updates/ud_7_03_02.php
  system/ee/legacy/libraries/Core.php
  system/ee/legacy/libraries/Fluid_field_parser.php
  tests/cypress/support/config/config.php
Labels: Bug: Accepted

#3419 Resolved #3112 where checkboxes could have been duplicated in long checkboxes lists
  system/ee/ExpressionEngine/View/_shared/form/field.php
Labels: Bug: Accepted

#3433 Bug/7.x/channel sets
  system/ee/ExpressionEngine/Controller/Channels/Sets.php
  system/ee/ExpressionEngine/Service/ChannelSet/Export.php
  system/ee/ExpressionEngine/Service/ChannelSet/Set.php
Labels: Bug: Accepted

#3415 Resolved issue where File module could show PHP error when using PHP 8.2
  system/ee/ExpressionEngine/Addons/file/mod.file.php
Labels: Bug: Accepted

#3455 Resolved #3429 where `channel="not X` parameter did not work correctly if channel X did not exist
  system/ee/ExpressionEngine/Addons/channel/mod.channel.php
Labels: Bug: Accepted

#3466 Resolved issue where it was impossible to edit Categories when using phone
  cp-styles/app/styles/components/_sidebar.scss
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#3308 Resolved #2112 where deleting too many logs could cause the system go out of memory
  system/ee/ExpressionEngine/Controller/Logs/Logs.php
Labels: Bug: Accepted

#3322 Optimize member stats sync on update
  system/ee/installer/updates/ud_6_03_04.php
Labels: enhancement

#3338 Resolved #758 where installation wizard did not work when PHP was configured to have no memory limit
  system/ee/installer/updater/ExpressionEngine/Updater/Service/Updater/RequirementsChecker.php
Labels: Bug: Accepted

#3339 Bug/6.x/status update (see description)
  system/ee/ExpressionEngine/Controller/Publish/Edit.php
  system/ee/ExpressionEngine/Model/Channel/ChannelEntry.php
  system/ee/ExpressionEngine/Model/Channel/Display/DefaultChannelLayout.php
  system/ee/ExpressionEngine/Model/Content/Display/FieldDisplay.php
  system/ee/ExpressionEngine/Model/Content/Display/LayoutTab.php
  system/ee/ExpressionEngine/Model/Status/Status.php
  system/ee/language/english/content_lang.php
Labels: Bug: Accepted

#3344 Resolved #1795 Where display of negative numerical field has - placed incorrectly for RTL text direction
  cp-styles/app/styles/base/_inputs.scss
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#3352 Improved counting members on role
  system/ee/ExpressionEngine/Model/Role/Role.php
Labels: enhancement: accepted

#3434 Bug/6.x/channel sets
  system/ee/ExpressionEngine/Controller/Channels/Sets.php
  system/ee/ExpressionEngine/Service/ChannelSet/Export.php
  system/ee/ExpressionEngine/Service/ChannelSet/Set.php
Labels: Bug: Accepted

#3420 Resolved #3112 where checkboxes could have been duplicated in long checkboxes lists
  system/ee/ExpressionEngine/View/_shared/form/field.php
Labels: Bug: Accepted

#3417 Resolved #3259 where certain coditionals in templates could generate PHP warning
  system/ee/ExpressionEngine/Library/Parser/Conditional/BooleanExpression.php
Labels: Bug: Accepted

#3408 Resolved #3397 where Template Routes page was showing deprecation notices when using PHP 8.2
  system/ee/legacy/libraries/template_router/Converters.php
  system/ee/legacy/libraries/template_router/Part.php
  system/ee/legacy/libraries/template_router/Route.php
  system/ee/legacy/libraries/template_router/converters/Max_length.php
  system/ee/legacy/libraries/template_router/converters/Min_length.php
  system/ee/legacy/libraries/template_router/converters/Regex.php
Labels: Bug: Accepted

#3405 Resolved #3402 where PHP 8.1 deprecation noticed were shown when bulk editing entries without Pages URL set but Pages module installed
  system/ee/ExpressionEngine/Addons/pages/tab.pages.php
Labels: Bug: Accepted

#3362 Resolved #3350 where PHP notice might be shown when parsing empty member field
  system/ee/ExpressionEngine/Model/Content/FieldModel.php
Labels: Bug: Accepted

#3373 Resolved #3371 where Grid fields could show PHP error when ExpressionEngine was updated from older version
  system/ee/ExpressionEngine/Addons/grid/ft.grid.php
Labels: Bug: Accepted

#3399 Resolved #3123 where having template records without template group in database would case PHP notices in template editor
  system/ee/ExpressionEngine/Controller/Design/Template.php
Labels: Bug: Accepted

#3530 Resolved issue where image manipulation could malfunction if the resize protocol was not set
  system/ee/legacy/libraries/Image_lib.php
Labels: Bug: Accepted

#3527 Resolved issue where running updater would try to create templates from files outside of site's template directory
  system/ee/ExpressionEngine/Library/Advisor/Advisor.php
  system/ee/legacy/libraries/Template.php
Labels: Bug: Accepted

#3524 Resolved issue where PHP warnings was shown when running `make:command` in CLI while on PHP 8.2
  system/ee/ExpressionEngine/Service/Generator/CommandGenerator.php
Labels: Bug: Accepted

#3517 Resolved issue when not all Pro Variables classes were loaded when creating new field
  system/ee/ExpressionEngine/Addons/pro_variables/ft.pro_variables.php
  system/ee/ExpressionEngine/Service/Template/Variables/ModifiableTrait.php
Labels: Bug: Accepted

#3516 Resolved #2666 where using Structure with dynamic channel queries caching on could cause some pages to display incorrectly
  system/ee/ExpressionEngine/Addons/structure/ext.structure.php
Labels: Bug: Accepted

#3407 Resolved #3384 where Deleting a Member, Member Select to Reassign Entries does not populate
  themes/ee/asset/javascript/src/cp/confirm_remove.js
Labels: Bug: Accepted

#3368 Resolved #2705 where "minimum rows" setting was not respected by File Grid fields
  system/ee/ExpressionEngine/Addons/grid/ft.file_grid.php
  system/ee/language/english/fieldtypes_lang.php
Labels: Bug: Accepted

#3366 Added validation for image manipulation names to not be numeric; #2884
  system/ee/ExpressionEngine/Model/File/FileDimension.php
  system/ee/ExpressionEngine/Service/Validation/Rule/NotNumeric.php
  system/ee/language/english/form_validation_lang.php
Labels: enhancement: accepted

#3359 Resolved #3349 where comment moderation preferences were not fully checked
  system/ee/ExpressionEngine/Addons/comment/mod.comment.php
Labels: Bug: Accepted

#3525 Resolved #3522 where early parsed Grids in Pro Variables would not render properly
  system/ee/ExpressionEngine/Service/Template/Variables/LegacyParser.php
Labels: Bug: Accepted

#3301 Resolved #3020 where "login as" functionality was broken if member had MFA enabled
  system/ee/ExpressionEngine/Controller/Members/Profile/Login.php
  system/ee/language/english/pro_lang.php
Labels: Bug: Accepted

#3196 Resolved #3099, #2178 where existing entries did not show up in Entry Manager if the user did not have editing permission on another channel
  system/ee/ExpressionEngine/Controller/Publish/Edit.php
Labels: Bug: Accepted

#3205 Added preference for TLS version used when sending email over SMTP; #2035
  system/ee/ExpressionEngine/Controller/Settings/Email.php
  system/ee/ExpressionEngine/Controller/Settings/Settings.php
  system/ee/language/english/settings_lang.php
  system/ee/legacy/libraries/Email.php
Labels: enhancement: accepted

#3462 Resolved #690 where is was possible to save required File Grid without files
  system/ee/ExpressionEngine/Addons/grid/ft.grid.php
  system/ee/ExpressionEngine/Addons/grid/libraries/Grid_lib.php
Labels: Bug: Accepted

#3459 Resolved #674 where having conflicting member_id in Member Import XML file was causing SQL error
  system/ee/ExpressionEngine/Controller/Utilities/MemberImport.php
Labels: Bug: Accepted

#3447 Resolved #3445 where wrong error message could be shown when creating a grid field
  system/ee/ExpressionEngine/Addons/grid/views/settings.php
Labels: Bug: Accepted

#3435 Resolved issue where some errors did not render properly when using custom error template
  system/ee/ExpressionEngine/Addons/channel/mod.channel.php
  system/ee/ExpressionEngine/Model/Template/GlobalVariable.php
  system/ee/ExpressionEngine/Model/Template/Snippet.php
  system/ee/ExpressionEngine/Service/Template/Variables/StandardGlobals.php
  system/ee/legacy/libraries/Csrf.php
  system/ee/legacy/libraries/Functions.php
  system/ee/legacy/libraries/Localize.php
  system/ee/legacy/libraries/Template.php
  system/ee/legacy/libraries/Typography.php
  system/ee/legacy/libraries/channel_entries_parser/Parser.php
Labels: Bug: Accepted

#3412 Resolved issue where not all messages were added to template processing log
  system/ee/legacy/libraries/Template.php
Labels: Bug: Accepted

#3369 Resolved #2705 where "minimum rows" setting was not respected by File Grid fields
  system/ee/ExpressionEngine/Addons/grid/ft.file_grid.php
  system/ee/language/english/fieldtypes_lang.php
Labels: Bug: Accepted

#3367 Added validation for image manipulation names to not be numeric; #2884
  system/ee/ExpressionEngine/Model/File/FileDimension.php
  system/ee/ExpressionEngine/Service/Validation/Rule/NotNumeric.php
  system/ee/language/english/form_validation_lang.php
Labels: enhancement: accepted

#3360 Resolved #3349 where comment moderation preferences were not fully checked
  system/ee/ExpressionEngine/Addons/comment/mod.comment.php
Labels: Bug: Accepted

#3204 Added preference for TLS version used when sending email over SMTP; #2035
  system/ee/ExpressionEngine/Controller/Settings/Email.php
  system/ee/ExpressionEngine/Controller/Settings/Settings.php
  system/ee/language/english/settings_lang.php
  system/ee/legacy/libraries/Email.php
Labels: enhancement

#3461 Resolved #690 where is was possible to save required File Grid without files
  system/ee/ExpressionEngine/Addons/grid/ft.grid.php
  system/ee/ExpressionEngine/Addons/grid/libraries/Grid_lib.php
Labels: Bug: Accepted

#3058 Resolved #3051 where Menu Manager was doubling rows when creating new Dropdown item
  themes/ee/asset/javascript/src/cp/modal_form.js
Labels: Bug: Accepted

#3422 Resolved #3421 where CLI extension hook generator had wrong info for `relationship_query`
  system/ee/ExpressionEngine/Service/Generator/Enums/Hooks.php
Labels: Bug: Accepted

#3418 Make 'Synchronize Upload Directory' utility set correct file type if it is not set; #3134
  system/ee/ExpressionEngine/Controller/Files/Uploads.php
Labels: enhancement: accepted

#3446 Resolved #3445 where wrong error message could be shown when creating a grid field
  system/ee/ExpressionEngine/Addons/grid/views/settings.php
Labels: Bug: Accepted

#3411 Resolved issue where not all messages were added to template processing log
  system/ee/legacy/libraries/Template.php
Labels: Bug: Accepted

#3562 Resolved issue where updated `underscore.js` was not included with ExpressionEngine build
  themes/ee/cp/js/build/vendor/underscore.js
  themes/ee/cp/js/src/vendor/underscore.js
Labels: Bug: Accepted

#3436 Resolved issue where some errors did not render properly when using custom error template
  system/ee/ExpressionEngine/Addons/channel/mod.channel.php
  system/ee/ExpressionEngine/Model/Template/GlobalVariable.php
  system/ee/ExpressionEngine/Model/Template/Snippet.php
  system/ee/legacy/libraries/Csrf.php
  system/ee/legacy/libraries/Functions.php
  system/ee/legacy/libraries/Localize.php
  system/ee/legacy/libraries/Template.php
  system/ee/legacy/libraries/Typography.php
  system/ee/legacy/libraries/channel_entries_parser/Parser.php
Labels: Bug: Accepted
