Repository ExpressionEngine/ExpressionEngine, pull requests merged in 2023-04, with the labels that each got.

#3140 Resolved #3135, #3047 where the columns in Entry Manager did not dynamically update if some column is not available
  system/ee/ExpressionEngine/Library/CP/EntryManager/ColumnFactory.php
  system/ee/ExpressionEngine/Library/CP/EntryManager/ColumnRenderer.php
  system/ee/ExpressionEngine/Library/CP/FileManager/ColumnRenderer.php
  system/ee/ExpressionEngine/Library/CP/FileManager/Traits/FileManagerTrait.php
Labels: Bug: Accepted

#3146 Resolved #3126 where Mass Notification Export utility did not work properly
  system/ee/ExpressionEngine/Library/Filesystem/Filesystem.php
Labels: Bug: Accepted

#3122 Fixed #3120 where duplicate status options with large number of statuses in cp
  system/ee/ExpressionEngine/Controller/Channels/Channels.php
Labels: Bug: Accepted

#3145 Resolved #3127 where PHP error was shown when creating shortcut from Pro Search log
  system/ee/ExpressionEngine/Addons/pro_search/mcp.pro_search.php
  system/ee/ExpressionEngine/Addons/pro_search/models/pro_search_shortcut_model.php
Labels: Bug: Accepted

#3149 Fixed #3130 where the filter control to add/delete columns doesn't do anything on File modal on publish
  system/ee/ExpressionEngine/Library/CP/FileManager/Traits/FileManagerTrait.php
  system/ee/ExpressionEngine/Service/Filter/FileManagerColumns.php
  system/ee/ExpressionEngine/View/files/index.php
  themes/ee/asset/javascript/src/cp/publish/entry-list.js
Labels: Bug: Accepted

#3141 Resolved #3135, #3047 where the columns in Entry Manager did not dynamically update if some column is not available
  system/ee/ExpressionEngine/Library/CP/EntryManager/ColumnFactory.php
  system/ee/ExpressionEngine/Library/CP/EntryManager/ColumnRenderer.php
Labels: Bug: Accepted

#3056 Resolved #2752 where cross-domain multi-site login was not working
  system/ee/ExpressionEngine/Addons/member/mod.member_auth.php
  system/ee/language/english/login_lang.php
  system/ee/legacy/controllers/ee.php
  system/ee/legacy/libraries/Auth.php
  system/ee/legacy/libraries/Core.php
  system/ee/legacy/libraries/Session.php
  tests/cypress/support/sql/more-roles.sql
Labels: Bug: Accepted

#3177 Resolved issue when deprecation message was shown by `exp:channel:entries` tag when using PHP 8.1
  system/ee/ExpressionEngine/Addons/channel/mod.channel.php
Labels: Bug: Accepted

#3055 Resolved #2752 where cross-domain multi-site login was not working
  system/ee/ExpressionEngine/Addons/member/mod.member_auth.php
  system/ee/language/english/login_lang.php
  system/ee/legacy/controllers/ee.php
  system/ee/legacy/libraries/Auth.php
  system/ee/legacy/libraries/Core.php
  system/ee/legacy/libraries/Session.php
  tests/cypress/support/sql/more-roles.sql
Labels: Bug: Accepted

#3155 Resolved #3129 where "extension missing" messages could be visible to guests even when the site is offline
  system/ee/legacy/libraries/Extensions.php
Labels: Bug: Accepted

#3163 Resolved issue where Live Preview did not work with Fluid fields
  system/ee/ExpressionEngine/Addons/fluid_field/ft.fluid_field.php
  system/ee/ExpressionEngine/Service/LivePreview/LivePreview.php
Labels: Bug: Accepted

#3229 Resolved issue where login form on front-end was showing incorrect error
  system/ee/ExpressionEngine/Addons/member/mod.member_auth.php
Labels: Bug: Accepted

#3226 Resolved #3235 where Live Preview did not work with Fluid fields
  system/ee/ExpressionEngine/Addons/fluid_field/ft.fluid_field.php
  system/ee/ExpressionEngine/Service/LivePreview/LivePreview.php
Labels: Bug: Accepted

#3227 Resolved issue where login form on front-end was showing incorrect error
  system/ee/ExpressionEngine/Addons/member/mod.member_auth.php
Labels: Bug: Accepted

#3176 Resolved #3027 where upload directories with angle brackets were not displayed correctly in file manager filters
  system/ee/ExpressionEngine/Library/CP/FileManager/Traits/FileManagerTrait.php
Labels: Bug: Accepted

#3180 Resolved #1099 where File Menu Width Remains Too Narrow
  cp-styles/app/styles/layout/_file-manager.scss
  themes/ee/asset/javascript/src/cp/files/picker.js
  themes/ee/cp/css/common.min.css
  themes/ee/cp/js/build/components/dropdown_button.js
  themes/ee/cp/js/src/components/dropdown_button.jsx
Labels: Bug: Accepted

#3179 Resolved #3147 where templates export did not work when using PHP 8.1
  system/ee/ExpressionEngine/Controller/Design/AbstractDesign.php
Labels: Bug: Accepted

#3183 Resolved #3152 where settings for RTE Pro Variables field were not saved
  system/ee/ExpressionEngine/Addons/pro_variables/mcp.pro_variables.php
  system/ee/ExpressionEngine/Addons/pro_variables/types/pro_rte/vt.pro_rte.php
  system/ee/ExpressionEngine/Addons/rte/ft.rte.php
Labels: Bug: Accepted

#3185 Resolved #3101 where autosaves table for new entry included entries from other channels
  system/ee/ExpressionEngine/Controller/Publish/AbstractPublish.php
  system/ee/ExpressionEngine/View/publish/partials/publish_form.php
Labels: Bug: Accepted

#3188 Resolved #3157 where the list of authors to reassign the entries when deleting member could be wrong
  system/ee/ExpressionEngine/Controller/Members/Members.php
  system/ee/ExpressionEngine/Controller/Members/Profile/Profile.php
Labels: Bug: Accepted

#3237 Resolved #3202 where searching in Categories filter in File Manager category did not work after changing another filter
  themes/ee/asset/javascript/src/cp/publish/entry-list.js
Labels: Bug: Accepted

#3240 Resolved #1899 Where the "link" HTML button didn't work as intended
  themes/ee/asset/javascript/src/jquery/plugins/markitup.js
Labels: Bug: Accepted

#3241 Resolved #1899 Where the "link" HTML button didn't work as intended
  themes/ee/asset/javascript/src/jquery/plugins/markitup.js
Labels: Bug: Accepted

#3238 Resolved #3202 where searching in Categories filter in File Manager category did not work after changing another filter
  themes/ee/asset/javascript/src/cp/publish/entry-list.js
Labels: Bug: Accepted

#3187 Resolved #3157 where the list of authors to reassign the entries when deleting member could be wrong
  system/ee/ExpressionEngine/Controller/Members/Members.php
  system/ee/ExpressionEngine/Controller/Members/Profile/Profile.php
Labels: Bug: Accepted

#3182 Resolved issue where built-in RTE field was giving error when using with Low Variables
  system/ee/ExpressionEngine/Addons/rte/ft.rte.php
Labels: Bug: Accepted

#3178 Resolved #3147 where templates export did not work when using PHP 8.1
  system/ee/ExpressionEngine/Controller/Design/AbstractDesign.php
Labels: Bug: Accepted

#3197 Resolved #3174 where min height of RTE field could be wrong when using different CKEditor configurations for same entry
  system/ee/ExpressionEngine/Addons/rte/Service/CkeditorService.php
Labels: Bug: Accepted

#3211 Optimize logging developer messages; #3057
  system/ee/legacy/libraries/Logger.php
Labels: enhancement

#3252 Resolved #3246 where not all checks for empty Grid or Fluid field worked correctly in templates when using PHP 8.1
  system/ee/legacy/libraries/channel_entries_parser/Parser.php
Labels: Bug: Accepted

#3254 Resolved #3245 where `0` could be displayed as empty string in template variables provided by add-ons
  system/ee/legacy/libraries/channel_entries_parser/components/Simple_variable.php
Labels: Bug: Accepted

#3265 Fixed #2028 where Installer/Updater does not respect the theme
  system/ee/ExpressionEngine/View/_templates/login.php
  system/ee/installer/views/container.php
Labels: UX

#3279 Resolved #510 where existing entries did not have correct value for toggle field after adding it and no prompt for update were made
  system/ee/ExpressionEngine/Addons/toggle/ft.toggle.php
  system/ee/language/english/admin_content_lang.php
  system/ee/legacy/helpers/custom_field_helper.php
Labels: Bug: Accepted

#3280 Resolved #2417 where PHP error could been shown when saving channel layout
  system/ee/ExpressionEngine/Model/Channel/ChannelLayout.php
Labels: Bug: Accepted

#3289 Resolved #846, #1840 where scroll immediately closes the sidebar on mobile screen
  themes/ee/asset/javascript/src/common.js
Labels: Bug: Accepted

#3294 Resolved #3272 where parsing order was not correct for add-ons that contain both module and plugin file
  system/ee/legacy/libraries/Template.php
Labels: Bug: Accepted

#3195 Resolved #3190 where pagination in File Manager did not respect permissions for upload directories
  system/ee/ExpressionEngine/Library/CP/FileManager/Traits/FileManagerTrait.php
Labels: Bug: Accepted

#3250 Add keyboard shortcut for saving Pro Variables
  system/ee/ExpressionEngine/Addons/pro_variables/mcp.pro_variables.php
Labels: Bug: Accepted

#3251 Resolved #3246 where not all checks for empty Grid or Fluid field worked correctly in templates when using PHP 8.1
  system/ee/legacy/libraries/channel_entries_parser/Parser.php
Labels: Bug: Accepted

#3253 Resolved #3245 where `0` could be displayed as empty string in template variables provided by add-ons
  system/ee/legacy/libraries/channel_entries_parser/components/Simple_variable.php
Labels: Bug: Accepted

#3264 Fixed #2028 where Installer/Updater does not respect the theme
  system/ee/ExpressionEngine/View/_templates/login.php
  system/ee/installer/views/container.php
Labels: UX

#3275 Resolved #3274 where special characters in URL for on-the-fly manipulated images were encoded twice
  system/ee/ExpressionEngine/Addons/file/ft.file.php
Labels: Bug: Accepted

#3281 Resolved #2417 where PHP error could been shown when saving channel layout
  system/ee/ExpressionEngine/Model/Channel/ChannelLayout.php
Labels: Bug: Accepted

#3288 Resolved #846, #1840 where scroll immediately closes the sidebar on mobile screen
  themes/ee/asset/javascript/src/common.js
Labels: Bug: Accepted

#3295 Resolved #3272 where parsing order was not correct for add-ons that contain both module and plugin file
  system/ee/legacy/libraries/Template.php
Labels: Bug: Accepted

#3212 Optimize logging developer messages; #3057
  system/ee/legacy/libraries/Logger.php
Labels: enhancement: accepted

#3198 Resolved #3174 where min height of RTE field could be wrong when using different CKEditor configurations for same entry
  system/ee/ExpressionEngine/Addons/rte/Service/CkeditorService.php
Labels: Bug: Accepted

#3235 Resolved #3222 where File icon in File field does not match field type
  cp-styles/app/styles/components/_file-field.scss
  themes/ee/asset/javascript/src/fields/file/control_panel.js
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#3303 Resolved #3302 where Structure was showing deprecation notices when using PHP 8.2
  system/ee/ExpressionEngine/Addons/structure/acc.structure.php
  system/ee/ExpressionEngine/Addons/structure/ext.structure.php
  system/ee/ExpressionEngine/Addons/structure/mod.structure.php
  system/ee/ExpressionEngine/Addons/structure/sql.structure.php
  system/ee/ExpressionEngine/Addons/structure/upd.structure.php
Labels: Bug: Accepted

#3199 Resolved #3191 where PHP errors could be shown when installing add-on that has fieldtype and module
  system/ee/legacy/libraries/addons/Addons_installer.php
Labels: Bug: Accepted
