Repository ExpressionEngine/ExpressionEngine, pull requests merged in 2023-01, with the labels that each got.

#2641 Improved PHP 8.1 support
  system/ee/ExpressionEngine/Library/Advisor/TemplateAdvisor.php
  system/ee/legacy/libraries/Template.php
Labels: Bug: Accepted

#2644 Resolved #786 where page moves to the top after saving new entry in a relationships modal
  cp-styles/app/styles/legacy/_app-overlay.less
  themes/ee/asset/javascript/src/common.js
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#2693 Add additional HTML elements to CP stylesheet; #2685
  cp-styles/app/styles/base/_inputs.scss
  cp-styles/app/styles/base/_typography.scss
  cp-styles/app/styles/components/_progress-bar.scss
  themes/ee/cp/css/common.min.css
Labels: enhancement

#2665 Resolved #2500 where reordering Grid with images had some issues
  themes/ee/asset/javascript/src/cp/grid.js
Labels: Bug: Accepted

#2664 Resolved #2663 where forgot password form could generate erroneous reset URLs
  system/ee/ExpressionEngine/Addons/member/mod.member_auth.php
Labels: Bug: Accepted

#2629 Retain pagination and filters on Entry Manager page after saving & closing entry; #111
  system/ee/ExpressionEngine/Addons/structure/ext.structure.php
  system/ee/ExpressionEngine/Controller/Publish/AbstractPublish.php
  system/ee/ExpressionEngine/Controller/Publish/Edit.php
  system/ee/ExpressionEngine/Library/CP/EntryManager/ColumnRenderer.php
  system/ee/ExpressionEngine/Library/CP/EntryManager/Columns/Title.php
  system/ee/ExpressionEngine/Library/CP/FileManager/Columns/Title.php
Labels: enhancement: accepted

#2602 Improved Pro Search collections page UI
  system/ee/ExpressionEngine/Addons/pro_search/mcp.pro_search.php
  system/ee/language/english/pro_search_lang.php
Labels: enhancement: accepted

#2707 Resolves issue with using lang entries in CLI command
  system/ee/ExpressionEngine/Cli/Commands/CommandMakeTemplateTag.php
  system/ee/ExpressionEngine/Service/Generator/TemplateTagGenerator.php
  system/ee/language/english/cli_lang.php
Labels: Bug: Accepted, EE7

#2708 Resolved #2700 where Pro Variables could show PHP notice
  system/ee/ExpressionEngine/View/_shared/table.php
Labels: Bug: Accepted, EE7

#2709 Add CLI command to generate jump files for add-ons
  system/ee/ExpressionEngine/Cli/Cli.php
  system/ee/ExpressionEngine/Cli/Commands/CommandListCommands.php
  system/ee/ExpressionEngine/Cli/Commands/CommandMakeJump.php
  system/ee/ExpressionEngine/Service/Generator/JumpsGenerator.php
  system/ee/ExpressionEngine/Service/Generator/stubs/jumps.php
  system/ee/ExpressionEngine/app.setup.php
  system/ee/language/english/cli_lang.php
Labels: needs documentation, development, EE7

#2694 Resolved issue with View Type preference not properly encoded
  composer.json
  composer.lock
  system/ee/ExpressionEngine/Service/File/ViewType.php
  vendor-bin/php-scoper/composer.lock
Labels: Bug: Accepted, EE7

#2689 Resolved #2658 where some parameters were not available for member management forms
  system/ee/ExpressionEngine/Addons/member/mod.member_images.php
  system/ee/ExpressionEngine/Addons/member/mod.member_memberlist.php
  system/ee/ExpressionEngine/Addons/member/mod.member_settings.php
Labels: enhancement: accepted

#2706 Resolved issue where Pro Search filters were using Low Search naming
  system/ee/ExpressionEngine/Addons/pro_search/libraries/Pro_search_filters.php
Labels: Bug: Accepted, EE7

#2699 Resolved #2679 where password validation URL was giving PHP error
  system/ee/ExpressionEngine/Addons/member/mod.member.php
  tests/cypress/cypress/integration/members/register.ee6.js
  tests/cypress/support/templates/default_site/mbr.group/register.html
Labels: Bug: Accepted

#2698 Resolved #2679 where password validation URL was giving PHP error
  system/ee/ExpressionEngine/Addons/member/mod.member.php
  tests/cypress/cypress/integration/members/register.ee6.js
  tests/cypress/support/templates/default_site/mbr.group/register.html
Labels: Bug: Accepted

#2716 Fixed bug when user leaves low search in install
  system/ee/ExpressionEngine/Addons/pro_search/libraries/Pro_search_filters.php
Labels: Bug: Accepted, EE7

#2720 Clean the qs values
  system/ee/ExpressionEngine/Controller/Publish/AbstractPublish.php
Labels: enhancement, EE7

#2719 Resolved issue with View Type preference not properly encoded
  system/ee/ExpressionEngine/Service/File/ViewType.php
Labels: Bug: Accepted, EE6

#2732 Reverts commits where there were issues in the header_sorts
  system/ee/ExpressionEngine/View/_shared/table.php
Labels: Bug: Accepted

#2736 Resolved #2735 where Text Formatter could show deprecation notices when using PHP 8.1
  system/ee/ExpressionEngine/Service/Formatter/Formats/Text.php
Labels: Bug: Accepted

#2726 Resolved issue where Channel Form grid has extra unneeded column
  system/ee/ExpressionEngine/View/_shared/table.php
Labels: Bug: Accepted

#2740 Resolved #2739 where PHP notice could have been shown when accessing plugin documentation when using PHP 8.1
  system/ee/ExpressionEngine/Controller/Addons/Addons.php
Labels: Bug: Accepted

#2742 Added ability to set template engine in template manager
  system/ee/ExpressionEngine/Controller/Design/Template.php
  system/ee/ExpressionEngine/Model/Template/Template.php
  system/ee/ExpressionEngine/Service/Model/FileSyncedModel.php
  system/ee/ExpressionEngine/Service/Model/Model.php
  system/ee/language/english/design_lang.php
  system/ee/legacy/libraries/api/Api_template_structure.php
Labels: enhancement: accepted

#2746 Resolved #2667 where errors for password resetting were not shown properly
  system/ee/ExpressionEngine/Addons/member/mod.member_auth.php
  system/ee/ExpressionEngine/Addons/member/mod.member_settings.php
Labels: Bug: Accepted

#2751 Resolved #2437 where building Pro Search Collection via URL did not work properly
  system/ee/ExpressionEngine/Addons/pro_search/addon.json
  system/ee/ExpressionEngine/Addons/pro_search/libraries/Pro_search_settings.php
  system/ee/ExpressionEngine/Addons/pro_search/mcp.pro_search.php
  system/ee/ExpressionEngine/Addons/pro_search/mod.pro_search.php
  system/ee/ExpressionEngine/Addons/pro_search/upd.pro_search.php
  system/ee/language/english/pro_search_lang.php
Labels: Bug: Accepted, EE7

#2733 Resolved #2661 where is was not possible to search template group and template at the same time in Pages tab
  system/ee/ExpressionEngine/Addons/pages/tab.pages.php
  system/ee/ExpressionEngine/Addons/select/ft.select.php
  system/ee/ExpressionEngine/View/_shared/form/fields/dropdown.php
  themes/ee/asset/javascript/src/fields/dropdown/dropdown.es6
  themes/ee/asset/javascript/src/fields/dropdown/dropdown.js
Labels: Bug: Accepted

#2762 Resolved #2759 where checkbox field with the name of "statuses" does not render correctly
  cp-styles/app/styles/components/_checkboxes-and-radios.scss
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#2584 Added setting for the day of week start; Updated date fieldtype to allow hiding localization buttons and not including time; #652
  system/ee/ExpressionEngine/Addons/date/ft.date.php
  system/ee/ExpressionEngine/Addons/date/views/publish.php
  system/ee/ExpressionEngine/Addons/member/mod.member_settings.php
  system/ee/ExpressionEngine/Controller/Members/Profile/Date.php
  system/ee/ExpressionEngine/Controller/Settings/General.php
  system/ee/ExpressionEngine/Model/Member/Gateway/MemberGateway.php
  system/ee/ExpressionEngine/Model/Member/Member.php
  system/ee/ExpressionEngine/Model/Site/Column/SystemPreferences.php
  system/ee/ExpressionEngine/Service/Filter/Date.php
  system/ee/ExpressionEngine/Service/JumpMenu/JumpMenu.php
  system/ee/installer/controllers/wizard.php
  system/ee/installer/schema/mysql_schema.php
  system/ee/installer/updates/ud_7_03_00.php
  system/ee/language/english/fieldtypes_lang.php
  system/ee/language/english/settings_lang.php
  system/ee/legacy/core/Config.php
  system/ee/legacy/libraries/Core.php
  system/ee/legacy/libraries/Localize.php
  system/ee/legacy/libraries/Session.php
  themes/ee/asset/javascript/src/cp/date_picker.js
Labels: enhancement: accepted

#2704 Allow making upload directories available for all MSM sites; #78
  system/ee/ExpressionEngine/Addons/file/ft.file.php
  system/ee/ExpressionEngine/Addons/filepicker/mcp.filepicker.php
  system/ee/ExpressionEngine/Addons/filepicker/upd.filepicker.php
  system/ee/ExpressionEngine/Addons/grid/ft.file_grid.php
  system/ee/ExpressionEngine/Addons/moblog/mcp.moblog.php
  system/ee/ExpressionEngine/Controller/Files/AbstractFiles.php
  system/ee/ExpressionEngine/Controller/Files/Files.php
  system/ee/ExpressionEngine/Controller/Files/Uploads.php
  system/ee/ExpressionEngine/Controller/Members/Roles/Roles.php
  system/ee/ExpressionEngine/Library/CP/FileManager/Traits/FileManagerTrait.php
  system/ee/ExpressionEngine/Library/Filesystem/Filesystem.php
  system/ee/ExpressionEngine/Model/File/UploadDestination.php
  system/ee/ExpressionEngine/Service/File/Upload.php
  system/ee/ExpressionEngine/View/files/index.php
  system/ee/language/english/filemanager_lang.php
  system/ee/legacy/libraries/File_field.php
  system/ee/legacy/libraries/Filemanager.php
  tests/cypress/cypress/integration/files/shared_upload_dir.ee6.js
  tests/cypress/support/templates/default_site/entries.group/files.html
Labels: enhancement: accepted

#2785 Resolved issue where saving Fluid without fields could result in PHP error
  system/ee/ExpressionEngine/Addons/fluid_field/ft.fluid_field.php
  system/ee/ExpressionEngine/Controller/Fields/Fields.php
Labels: Bug: Accepted

#2779 Resolved issue where validation error was not properly thrown when saving a Grid in a Pro Variable
  system/ee/ExpressionEngine/Addons/pro_variables/types/pro_grid/vt.pro_grid.php
  system/ee/ExpressionEngine/View/_shared/table.php
Labels: Bug: Accepted

#2773 Resolved #2761 where Structure could show PHP warning when used with third-party forms
  system/ee/ExpressionEngine/Addons/structure/tab.structure.php
Labels: Bug: Accepted

#2770 Resolved #2758 where reordering did not always work properly in third-party grids
  themes/ee/asset/javascript/src/cp/grid.js
  themes/ee/asset/javascript/src/jquery/plugins/ee_table_reorder.js
Labels: Bug: Accepted

#2768 Resolved #2759 where checkbox field with the name of "statuses" did not always render correctly
  cp-styles/app/styles/components/_checkboxes-and-radios.scss
  system/ee/ExpressionEngine/Controller/Channels/Channels.php
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#2766 Added options for different display layouts for File Grid fields; #2764
  system/ee/ExpressionEngine/Addons/grid/ft.file_grid.php
  system/ee/language/english/fieldtypes_lang.php
Labels: enhancement: accepted

#2756 Resolved issue when files on non-local filesystem could not be resized or cropped from CP
  system/ee/ExpressionEngine/Controller/Files/File.php
  system/ee/ExpressionEngine/Library/Filesystem/Filesystem.php
  system/ee/legacy/libraries/Filemanager.php
Labels: Bug: Accepted
