Repository ExpressionEngine/ExpressionEngine, pull requests merged in 2023-02, with the labels that each got.

#2767 Added options for different display layouts for File Grid fields; #2764
  system/ee/ExpressionEngine/Addons/grid/ft.file_grid.php
  system/ee/language/english/fieldtypes_lang.php
Labels: enhancement: accepted

#2791 Resolved #2356 where Preview button was still visible when preview turned off in channel preferences
  system/ee/ExpressionEngine/Controller/Publish/AbstractPublish.php
Labels: Bug: Accepted

#2793 Resolved #2653 where Radio and Select fields were showing values and not labels in Entry Manager
  system/ee/ExpressionEngine/Addons/radio/ft.radio.php
  system/ee/ExpressionEngine/Addons/select/ft.select.php
Labels: Bug: Accepted

#2810 Resolved #2312 where conditional fields depending on radio button could be not loaded correctly when creating new entry
  system/ee/ExpressionEngine/Addons/radio/EvaluationRules/Matches.php
  system/ee/ExpressionEngine/Addons/radio/EvaluationRules/NotMatches.php
  system/ee/ExpressionEngine/Service/ConditionalFields/Evaluator.php
  system/ee/ExpressionEngine/Service/ConditionalFields/Factory.php
Labels: Bug: Accepted

#2803 Resolved issue when password validation did not work properly in some cases
  system/ee/ExpressionEngine/Addons/member/mod.member_auth.php
Labels: Bug: Accepted

#2796 Resolved #2784 where having ungrouped fields could cause group filter to malfunction in Field manager
  system/ee/ExpressionEngine/Controller/Fields/Fields.php
Labels: Bug: Accepted

#2792 Resolved #2653 where Radio and Select fields were showing values and not labels in Entry Manager
  system/ee/ExpressionEngine/Addons/radio/ft.radio.php
  system/ee/ExpressionEngine/Addons/select/ft.select.php
Labels: Bug: Accepted

#2738 Resolved #2737 where templates that require authentication could show PHP notice
  system/ee/legacy/libraries/Template.php
Labels: Bug: Accepted

#2745 Resolved #2667 where errors for password resetting were not shown properly
  system/ee/ExpressionEngine/Addons/member/mod.member_auth.php
  system/ee/ExpressionEngine/Addons/member/mod.member_settings.php
Labels: Bug: Accepted

#2812 Resolved #2808 where some servers did not accept SVG files to be uploaded into image-only directory
  system/ee/ExpressionEngine/Library/Mime/MimeType.php
Labels: Bug: Accepted

#2815 Resolved #2813 where select listing box bursts out of frame if page names are long.
  cp-styles/app/styles/components/_select-popup.scss
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#2811 Resolved #2808 where some servers did not accept SVG files to be uploaded into image-only directory
  system/ee/ExpressionEngine/Library/Mime/MimeType.php
Labels: Bug: Accepted

#2790 Resolved #2356 where Preview button was still visible when preview turned off in channel preferences
  system/ee/ExpressionEngine/Controller/Publish/AbstractPublish.php
Labels: Bug: Accepted

#2795 Resolved #2765 where using `ee()->table->set_data()` was not possible outside of Control Panel
  system/ee/legacy/libraries/Table.php
Labels: Bug: Accepted

#2794 Resolved #2765 where using `ee()->table->set_data()` was not possible outside of Control Panel
  system/ee/legacy/libraries/Table.php
Labels: Bug: Accepted

#2805 Resolved #2639 where animation was removed from GIF files during upload
  system/ee/legacy/libraries/Filemanager.php
Labels: Bug: Accepted

#2809 Resolved #2312 where conditional fields depending on radio button could be not loaded correctly when creating new entry
  system/ee/ExpressionEngine/Addons/radio/EvaluationRules/Matches.php
  system/ee/ExpressionEngine/Addons/radio/EvaluationRules/NotMatches.php
  system/ee/ExpressionEngine/Service/ConditionalFields/EvaluationRules/EvaluationRuleInterface.php
  system/ee/ExpressionEngine/Service/ConditionalFields/Evaluator.php
  system/ee/ExpressionEngine/Service/ConditionalFields/Factory.php
Labels: Bug: Accepted

#2831 Resolved #1644 where Edit Profile form could show error when used on same page with channel entries tag
  system/ee/ExpressionEngine/Addons/member/mod.member_settings.php
Labels: Bug: Accepted

#2832 Resolved #2829 where entry search in mobile view was not working
  cp-styles/app/styles/components/_filter-bar.scss
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#2799 Resolved #2233 where cloning entry without comments could generate PHP deprecation notices
  system/ee/ExpressionEngine/Service/Model/Column/ColumnObject/Timestamp.php
Labels: Bug: Accepted

#2823 Resolved issue when saving Grid field from third-party code could behave incorrectly
  system/ee/ExpressionEngine/Addons/relationship/ft.relationship.php
Labels: Bug: Accepted

#2845 Resolved #2838 where the new related entry modal generates JS errors
  .github/workflows/tests-minimal.yml
  .github/workflows/tests.yml
  .github/workflows/unit-tests.yml
  tests/cypress/cypress/integration/field/field_combinations.ee6.js
  themes/ee/cp/js/build/components/relationship.js
  themes/ee/cp/js/src/components/relationship.jsx
Labels: Bug: Accepted

#2840 Resolved #2481 where member count query was suboptimal
  .github/workflows/unit-tests.yml
  build-tools/build.json
  system/ee/ExpressionEngine/Addons/pro/Service/Access/Access.php
  system/ee/ExpressionEngine/Tests/bootstrap.php
  system/ee/installer/controllers/wizard.php
  system/ee/installer/schema/mysql_schema.php
  system/ee/installer/updates/ud_7_02_10.php
  system/ee/legacy/libraries/Core.php
  tests/cypress/cypress.json
  tests/cypress/support/config/config.php
  themes/ee/asset/javascript/src/cp/global_start.js
Labels: Bug: Accepted, performance

#2757 search module updates
  system/ee/ExpressionEngine/Addons/fluid_field/ft.fluid_field.php
  system/ee/ExpressionEngine/Addons/search/mod.search.php
  system/ee/legacy/helpers/search_helper.php
Labels: Bug: Accepted

#2677 Added per-channel setting to enforce automatic URL titles for entries; #952; #2645; #183
  system/ee/ExpressionEngine/Addons/text/ft.text.php
  system/ee/ExpressionEngine/Controller/Channels/Channels.php
  system/ee/ExpressionEngine/Controller/Publish/AbstractPublish.php
  system/ee/ExpressionEngine/Model/Channel/Channel.php
  system/ee/ExpressionEngine/Model/Channel/ChannelEntry.php
  system/ee/ExpressionEngine/Tests/ExpressionEngine/Service/Template/Variables/LegacyParserTest.php
  system/ee/ExpressionEngine/View/_shared/form/field.php
  system/ee/installer/schema/mysql_schema.php
  system/ee/installer/updates/ud_7_03_00.php
  system/ee/language/english/channel_lang.php
Labels: enhancement
