Repository ExpressionEngine/ExpressionEngine, pull requests merged in 2023-08, with the labels that each got.

#3393 Resolved #442 where some code was not formatted well
  system/ee/legacy/libraries/Functions.php
Labels: refactoring

#3541 Include Entry ID when searching in Relationship field; #3537
  system/ee/ExpressionEngine/Addons/relationship/libraries/EntryList.php
  tests/cypress/cypress/integration/publish/relationship.ee6.js
Labels: enhancement: accepted, test covered, docs covered

#3542 Resolved #3538 where validation for Field Group name was too strict
  system/ee/ExpressionEngine/Model/Channel/ChannelField.php
  system/ee/ExpressionEngine/Model/Channel/ChannelFieldGroup.php
Labels: Bug: Accepted

#3597 Resolved #3596 where duplicate entry dates could cause inconsistent ordering in Entry Manager
  system/ee/ExpressionEngine/Controller/Publish/Edit.php
Labels: Bug: Accepted

#3606 Resolved issue where PHP warning could have been shown when using Grid with Pro Variables
  system/ee/ExpressionEngine/Addons/grid/ft.grid.php
Labels: Bug: Accepted

#3600 Resolved #3595 where File field did not present explanation of assigned upload directory on other MSM site
  system/ee/ExpressionEngine/Addons/file/ft.file.php
  system/ee/ExpressionEngine/Addons/grid/ft.file_grid.php
  system/ee/language/english/fieldtypes_lang.php
Labels: Bug: Accepted

#3624 Resolved #3623 where printing website pages could include graphical elements from the Dock.
  frontedit/package-lock.json
  frontedit/package.json
  frontedit/src/scss/_dock.scss
  system/ee/ExpressionEngine/Addons/pro/Service/Dock/DockFactory.php
  themes/ee/pro/css/fronteditor.min.css
Labels: enhancement

#3631 Resolved issue where JavaScript error could be shown when accessing add-on settings
  themes/ee/asset/javascript/src/fields/file/drag_and_drop_upload.es6
  themes/ee/asset/javascript/src/fields/file/drag_and_drop_upload.js
Labels: Bug: Accepted

#3640 Resolved #3634 where having MSM-shared upload directory would cause Pages to be saved to wrong site
  system/ee/legacy/models/file_upload_preferences_model.php
Labels: Bug: Accepted

#3674 Resolved issue when selecting subfolder in file field was showing incorrect message in upload component
  themes/ee/asset/javascript/src/fields/file/drag_and_drop_upload.es6
  themes/ee/asset/javascript/src/fields/file/drag_and_drop_upload.js
Labels: Bug: Accepted

#3607 Resolved #3347 where members without permission to edit own entries could still access those with direct link
  system/ee/ExpressionEngine/Controller/Publish/Edit.php
  system/ee/ExpressionEngine/Controller/Publish/Publish.php
Labels: Bug: Accepted

#3647 Resolved issue where field group names were made lowercase in Fluid
  system/ee/legacy/libraries/Fluid_field_parser.php
Labels: Bug: Accepted

#3657 Resolved #2666 where using Dynamic query caching caused pagination on Structure listing being inaccurate
  system/ee/ExpressionEngine/Addons/channel/mod.channel.php
  system/ee/ExpressionEngine/Addons/structure/ext.structure.php
Labels: Bug: Accepted

#3659 Resolved issue where it was not possible to save loaded revision if Fluid field has some fields deleted; Resolved #3639 where is was not possible to save loaded revision with removed Grid rows; Resolved #3529 where records for Grid and Relationship fields were still left in database after removing from Fluid
  system/ee/ExpressionEngine/Addons/fluid_field/ft.fluid_field.php
  system/ee/ExpressionEngine/Addons/grid/libraries/Grid_lib.php
  system/ee/ExpressionEngine/Controller/Publish/AbstractPublish.php
  system/ee/legacy/models/grid_model.php
Labels: Bug: Accepted

#3665 Resolved #3663 where subdirectories were assigned to wrong site when using MSM
  system/ee/ExpressionEngine/Controller/Files/Files.php
  system/ee/installer/updates/ud_7_03_09.php
  system/ee/legacy/libraries/Core.php
  tests/cypress/cypress/integration/files/msm.ee6.js
  tests/cypress/cypress/integration/files/subfolders.ee6.js
Labels: Bug: Accepted

#3688 Resolved #3689 where PHP error could be shown when accessing custom fields
  system/ee/legacy/libraries/api/Api_channel_fields.php
Labels: Bug: Accepted

#3697 Resolved #3689 where PHP error could be shown when accessing custom fields
  system/ee/legacy/libraries/api/Api_channel_fields.php
Labels: Bug: Accepted

#3577 Resolved #3568 where deselecting all template access for Role in one MSM site would also deselect it on other sites
  system/ee/ExpressionEngine/Controller/Members/Roles/Roles.php
Labels: Bug: Accepted

#3391 Resolved #532 where index template could be deleted but then immediately recreated
  system/ee/ExpressionEngine/Controller/Design/AbstractDesign.php
Labels: Bug: Accepted

#3610 Fixed issue when styling in Grid field was not accurate when sorting
  cp-styles/app/styles/components/_grid-field.scss
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#3501 Reduced the number of SQL queries when performing search in Entry Manager
  system/ee/ExpressionEngine/Service/EntryListing/EntryListing.php
Labels: enhancement: accepted

#3651 Resolved issue where navigating subfolders in File Manager did not retain filers and sorting
  system/ee/ExpressionEngine/Controller/Files/Files.php
  system/ee/ExpressionEngine/Library/CP/FileManager/Columns/Thumbnail.php
  system/ee/ExpressionEngine/Library/CP/FileManager/Columns/Title.php
  system/ee/ExpressionEngine/Library/CP/FileManager/Traits/FileManagerTrait.php
Labels: Bug: Accepted

#3662 Change PHP variable name to avoid out-of-scope reassignment (EE 7)
  system/ee/legacy/libraries/Template.php
Labels: Bug: Accepted

#3394 Resolved #3383 where loading File Grid fields with many rows was slow
  system/ee/ExpressionEngine/Addons/file/views/publish.php
Labels: Bug: Accepted

#3655 Enabled additional caching in Structure
  system/ee/ExpressionEngine/Addons/structure/sql.structure.php
Labels: enhancement

#3681 Resolved issue where Download link for files using on-local storage adapters did not work
  system/ee/ExpressionEngine/Controller/Files/File.php
Labels: Bug: Accepted

#3687 Resolve conflicts in scoped dependency functions
  composer.json
  scoper.fix.php
Labels: Bug: Accepted

#3690 Resolved #3686 when having Minimum rows setting for File Grid higher than 1 would prevent entry from saving
  system/ee/ExpressionEngine/Addons/grid/ft.file_grid.php
  tests/cypress/cypress/integration/publish/publish.ee6.js
Labels: Bug: Accepted, test covered

#3648 Added display of seconds for revisions and autosaves; #3644
  system/ee/ExpressionEngine/Controller/Publish/AbstractPublish.php
  system/ee/ExpressionEngine/View/publish/partials/revision_badge.php
Labels: enhancement: accepted

#3695 Resolved issue where the status indicator was not displayed after searching in the Relationships field.
  themes/ee/asset/javascript/src/components/select_list.es6
  themes/ee/asset/javascript/src/components/select_list.js
Labels: Bug: Accepted

#3511 Improved Control Panel accessibility for using screen readers
  system/ee/ExpressionEngine/Addons/colorpicker/ft.colorpicker.php
  system/ee/ExpressionEngine/Addons/fluid_field/views/modal.php
  system/ee/ExpressionEngine/Addons/spam/View/modal.php
  system/ee/ExpressionEngine/Controller/Channels/AbstractChannels.php
  system/ee/ExpressionEngine/Controller/Members/Members.php
  system/ee/ExpressionEngine/Controller/Members/Profile/Profile.php
  system/ee/ExpressionEngine/Controller/Publish/AbstractPublish.php
  system/ee/ExpressionEngine/View/_shared/filters/date.php
  system/ee/ExpressionEngine/View/_shared/filters/entrykeyword.php
  system/ee/ExpressionEngine/View/_shared/filters/filter.php
  system/ee/ExpressionEngine/View/_shared/filters/keyword.php
  system/ee/ExpressionEngine/View/_shared/filters/perpage.php
  system/ee/ExpressionEngine/View/_shared/footer.php
  system/ee/ExpressionEngine/View/_shared/form/buttons.php
  system/ee/ExpressionEngine/View/_shared/form/condition/condition-rule.php
  system/ee/ExpressionEngine/View/_shared/form/condition/condition-set.php
  system/ee/ExpressionEngine/View/_shared/form/field.php
  system/ee/ExpressionEngine/View/_shared/form/fields/toggle.php
  system/ee/ExpressionEngine/View/_shared/form/mini_grid.php
  system/ee/ExpressionEngine/View/_shared/header.php
  system/ee/ExpressionEngine/View/_shared/idle-modal.php
  system/ee/ExpressionEngine/View/_shared/modal.php
  system/ee/ExpressionEngine/View/_shared/sidebar/navigation/navigation.php
  system/ee/ExpressionEngine/View/_shared/table-list.php
  system/ee/ExpressionEngine/View/_shared/table.php
  system/ee/ExpressionEngine/View/_shared/upgrade_success_banner.php
  system/ee/ExpressionEngine/View/_templates/default-nav.php
  system/ee/ExpressionEngine/View/_templates/login.php
  system/ee/ExpressionEngine/View/account/reset_password.php
  system/ee/ExpressionEngine/View/design/index.php
  system/ee/ExpressionEngine/View/files/_delete_modal.php
  system/ee/ExpressionEngine/View/members/pending.php
  system/ee/ExpressionEngine/View/settings/consents/destructive_modal.php
  system/ee/ExpressionEngine/View/utilities/communicate/body-field.php
  system/ee/ExpressionEngine/View/utilities/communicate/sent.php
  system/ee/ExpressionEngine/View/utilities/query/index.php
  system/ee/ExpressionEngine/View/utilities/sandr.php
  system/ee/ExpressionEngine/View/utilities/sql/manager.php
  system/ee/ExpressionEngine/View/utilities/translate/languages.php
  system/ee/ExpressionEngine/View/utilities/translate/list.php
  system/ee/language/english/cp_lang.php
  system/ee/legacy/helpers/form_helper.php
  system/ee/legacy/libraries/Cp.php
  themes/ee/asset/javascript/src/components/filters.es6
  themes/ee/asset/javascript/src/components/filters.js
  themes/ee/asset/javascript/src/components/select_list.es6
  themes/ee/asset/javascript/src/components/select_list.js
  themes/ee/asset/javascript/src/cp/passwords.js
  themes/ee/cp/js/build/components/colorpicker.js
  themes/ee/cp/js/src/components/colorpicker.tsx
Labels: accessibility

#3585 Resolved #3583 where RSS Parser user guide was referencing non-existing feed
  system/ee/ExpressionEngine/Addons/rss_parser/README.md
Labels: Bug: Accepted

#3598 Resolved #3596 where duplicate entry dates could cause inconsistent ordering in Entry Manager
  system/ee/ExpressionEngine/Controller/Publish/Edit.php
Labels: Bug: Accepted

#3658 Resolved issue where it was not possible to save loaded revision if Fluid field has some fields deleted; Resolved #3639 where is was not possible to save loaded revision with removed Grid rows; Resolved #3529 where records for Grid and Relationship fields were still left in database after removing from Fluid
  system/ee/ExpressionEngine/Addons/fluid_field/ft.fluid_field.php
  system/ee/ExpressionEngine/Addons/grid/libraries/Grid_lib.php
  system/ee/ExpressionEngine/Controller/Publish/AbstractPublish.php
  system/ee/legacy/fieldtypes/EE_Fieldtype.php
  system/ee/legacy/models/grid_model.php
Labels: Bug: Accepted

#3661 Change PHP variable name to avoid out-of-scope reassignment (EE 6)
  system/ee/legacy/libraries/Template.php
Labels: Bug: Accepted

#3668 Resolved #2666 where using Dynamic query caching caused pagination on Structure listing being inaccurate
  system/ee/ExpressionEngine/Addons/channel/mod.channel.php
Labels: Bug: Accepted

#3675 Resolved #3637 where using File field limited to upload directory on other site would result in JavaScript error
  system/ee/ExpressionEngine/Addons/file/ft.file.php
  system/ee/ExpressionEngine/Addons/grid/ft.file_grid.php
  system/ee/language/english/fieldtypes_lang.php
  system/ee/legacy/libraries/File_field.php
  themes/ee/asset/javascript/src/fields/file/drag_and_drop_upload.es6
  themes/ee/asset/javascript/src/fields/file/drag_and_drop_upload.js
Labels: Bug: Accepted

#3683 Resolved #3680 where term Snippet was still used in error message
  system/ee/legacy/libraries/Template.php
Labels: Bug: Accepted

#3693 Resolved issue where Channel form grid has duplicated label for every single row
  themes/ee/cform/css/eecms-cform.min.css
Labels: Bug: Accepted

#3315 Resolved #1788 where HTML Buttons were loaded with Channel Form even when not in use
  system/ee/ExpressionEngine/Addons/channel/libraries/channel_form/Channel_form_lib.php
  system/ee/ExpressionEngine/Addons/textarea/ft.textarea.php
Labels: Bug: Accepted

#3413 Resolved #200 where template layouts did not properly work with channel form
  system/ee/legacy/libraries/Template.php
Labels: Bug: Accepted

#3730 Resolved issue where the user was redirected to different page after saving Front-End Editing Settings
  system/ee/ExpressionEngine/Addons/pro/Controller/Settings/Frontedit.php
Labels: Bug: Accepted

#3720 Resolved issue where PHP notice was shown when running updater using PHP 8.2
  system/ee/installer/controllers/wizard.php
  tests/cypress/cypress/integration/z_installer/updater.ee6.js
Labels: Bug: Accepted

#3726 Resolved #3718 where edit links were showing up in Relationship field even for entries where user had no permissions
  system/ee/ExpressionEngine/Addons/relationship/ft.relationship.php
  system/ee/ExpressionEngine/Addons/relationship/libraries/EntryList.php
  themes/ee/asset/javascript/src/components/select_list.es6
  themes/ee/asset/javascript/src/components/select_list.js
  themes/ee/cp/js/build/components/relationship.js
  themes/ee/cp/js/src/components/relationship.jsx
Labels: Bug: Accepted

#3717 Resolved #2814 where Date picker wasn't always showing calendar when manually entering date into a date field
  themes/ee/asset/javascript/src/cp/date_picker.js
Labels: Bug: Accepted

#3652 Resolved #3636 where searching in File Manager while having Upload Directory selected did not include files in subfolders
  system/ee/ExpressionEngine/Library/CP/FileManager/Traits/FileManagerTrait.php
Labels: Bug: Accepted

#3474 Reduce the number of queries when fetching templates by caching some
  system/ee/legacy/libraries/Template.php
Labels: enhancement
