Repository ExpressionEngine/ExpressionEngine, pull requests merged in 2023-10, with the labels that each got.

#3793 Fixed JS replacement which added S=0 to beginning of URL
  themes/ee/asset/javascript/src/cp/global_start.js
Labels: Bug: Accepted

#3788 Resolved #3772 where ExpressionEngine News dashboard widgets was not using date fomatting preference
  system/ee/ExpressionEngine/Addons/pro/widgets/eecms_news.php
Labels: Bug: Accepted

#3783 Resolved #3759 when pressing Ctrl+S with Redactor editor being in full screen mode would cause the field content to be erased
  themes/ee/asset/javascript/src/common.js
Labels: Bug: Accepted

#3782 Resolved #3754 where PHP deprecation notice could be shown when using File Grid with file column empty
  system/ee/ExpressionEngine/Addons/file/ft.file.php
  tests/cypress/cypress/integration/publish/publish.ee6.js
  tests/cypress/support/templates/default_site/entries.group/file-grid.html
Labels: Bug: Accepted

#3773 Updated ColorPicker fieldtype so it could be used with Channel Form
  system/ee/ExpressionEngine/Addons/colorpicker/ft.colorpicker.php
  themes/ee/cform/css/eecms-cform.min.css
Labels: Bug: Accepted

#3748 Resolved #3743 where invisible characters in filenames caused corrupt path errors
  system/ee/ExpressionEngine/Library/Filesystem/Filesystem.php
  system/ee/legacy/libraries/Filemanager.php
  system/ee/legacy/libraries/Upload.php
Labels: Bug: Accepted

#3785 Resolved #3762 where selection of checkboxes in Grid with values containing single quotes was not re-populated after saving an entry
  system/ee/ExpressionEngine/Addons/checkboxes/ft.checkboxes.php
Labels: Bug: Accepted

#3787 Resolved #3766 where using invalid modifier when chaining on-the-fly image manipulations would cause PHP warning
  system/ee/ExpressionEngine/Addons/file/ft.file.php
Labels: Bug: Accepted

#3786 Resolved #3762 where selection of checkboxes in Grid with values containing single quotes was not re-populated after saving an entry
  system/ee/ExpressionEngine/Addons/checkboxes/ft.checkboxes.php
Labels: Bug: Accepted

#3784 Resolved #3759 when pressing Ctrl+S with Redactor editor being in full screen mode would cause the field content to be erased
  themes/ee/asset/javascript/src/common.js
Labels: Bug: Accepted

#3377 Added `primary_role_id` parameter for `exp:channel:entries` to work same as older `group_id`; #1353
  system/ee/ExpressionEngine/Addons/channel/mod.channel.php
Labels: enhancement: accepted

#3817 Resolved #3808 where PHP deprecation messages could be shown when saving entry using PHP 8.2
  system/ee/ExpressionEngine/Service/Model/Column/Serialized/CommaDelimited.php
  system/ee/ExpressionEngine/Service/Model/Column/Serialized/PipeDelimited.php
  system/ee/legacy/database/DB_driver.php
Labels: Bug: Accepted

#3826 Resolved #3825 where PHP deprecation error could be shown when using some third-party fieldtypes in Fluid field
  system/ee/ExpressionEngine/Model/Content/FieldFacade.php
Labels: Bug: Accepted

#3849 Resolved #3841 where `foreign_chars` config was missing commonly used symbol
  system/ee/ExpressionEngine/Config/foreign_chars.php
Labels: Bug: Accepted

#3827 Resolved #3745 where Color picker not working inside grid
  cp-styles/app/styles/components/_colorpicker.scss
  themes/ee/cp/css/common.min.css
  themes/ee/cp/js/build/bootstrap/dropdown-controller.js
  themes/ee/cp/js/build/components/colorpicker.js
  themes/ee/cp/js/src/bootstrap/dropdown-controller.js
  themes/ee/cp/js/src/components/colorpicker.tsx
Labels: Bug: Accepted

#3843 Added possibility to collapse categories in control panel #2917
  cp-styles/app/styles/components/_list-group.scss
  themes/ee/asset/javascript/src/cp/channel/category_reorder.js
  themes/ee/asset/javascript/src/jquery/plugins/nestable.js
  themes/ee/cp/css/common.min.css
Labels: enhancement

#3823 Added `{folder_id}` variable and parameter for subfolder support in `exp:file:entries` tag; #3820
  system/ee/ExpressionEngine/Addons/file/mod.file.php
  system/ee/legacy/libraries/File_field.php
  tests/cypress/cypress/integration/files/shared_upload_dir.ee6.js
  tests/cypress/cypress/integration/files/subfolders.ee6.js
  tests/cypress/support/templates/default_site/entries.group/file-entries.html
  tests/cypress/support/templates/default_site/entries.group/files.html
Labels: enhancement, test covered, docs covered
