Repository ExpressionEngine/ExpressionEngine, pull requests merged in 2023-11, with the labels that each got.

#2821 Added global variables for logged in user's avatar; #2583
  system/ee/legacy/libraries/Template.php
  tests/cypress/cypress/integration/content/global_variables.ee6.js
  tests/cypress/support/templates/default_site/global_variables.group/index.html
Labels: enhancement, test covered

#3716 Enable passing through MySQL PDO configuration from config file; #2989; #3427; Only set MySQL collation explicitely if it's different than default
  system/ee/ExpressionEngine/Service/Database/DBConfig.php
  system/ee/legacy/database/DB_driver.php
  system/ee/legacy/database/drivers/mysqli/mysqli_connection.php
Labels: performance, development, docs covered

#3713 Enabled logging in using email address; #2931
  system/ee/ExpressionEngine/Addons/member/mod.member_auth.php
  system/ee/ExpressionEngine/View/account/login.php
  tests/cypress/cypress/integration/cp/login.ee6.js
  tests/cypress/cypress/integration/members/login.ee6.js
Labels: enhancement, test covered

#3638 Added more variables to address position of field in group inside Fluid field
  system/ee/legacy/libraries/Fluid_field_parser.php
Labels: enhancement

#3560 Resolved #3489 where `member_rows` variable in `exp:member:memberlist` did not support `backspace` parameter
  system/ee/ExpressionEngine/Addons/member/mod.member_memberlist.php
  tests/cypress/cypress/integration/members/member_list.ee6.js
  tests/cypress/support/templates/default_site/members.group/memberlist-backspace.html
Labels: Bug: Accepted, test covered, docs covered

#3505 Enabled showing field short names on Entry Publish page; #3340
  .github/workflows/tests-minimal.yml
  .github/workflows/tests.yml
  build-tools/build.json
  cp-styles/app/styles/components/_badge.scss
  cp-styles/app/styles/components/_fieldsets.scss
  cp-styles/app/styles/components/_grid-field.scss
  system/ee/ExpressionEngine/Addons/fluid_field/ft.fluid_field.php
  system/ee/ExpressionEngine/Addons/fluid_field/views/field.php
  system/ee/ExpressionEngine/Addons/fluid_field/views/fieldgroup.php
  system/ee/ExpressionEngine/Addons/grid/ft.grid.php
  system/ee/ExpressionEngine/Addons/grid/libraries/Grid_lib.php
  system/ee/ExpressionEngine/Controller/Members/Roles/Roles.php
  system/ee/ExpressionEngine/Model/Channel/ChannelFieldGroup.php
  system/ee/ExpressionEngine/Model/Content/Display/FieldDisplay.php
  system/ee/ExpressionEngine/Model/Content/FieldFacade.php
  system/ee/ExpressionEngine/Model/Role/RoleSetting.php
  system/ee/ExpressionEngine/Tests/bootstrap.php
  system/ee/ExpressionEngine/View/_shared/table.php
  system/ee/ExpressionEngine/View/publish/partials/field_name_badge.php
  system/ee/ExpressionEngine/View/publish/partials/publish_form.php
  system/ee/installer/controllers/wizard.php
  system/ee/installer/schema/mysql_schema.php
  system/ee/installer/updates/ud_7_04_00.php
  system/ee/language/english/members_lang.php
  system/ee/legacy/libraries/Core.php
  tests/cypress/channel_sets/channel-with-fluid-field.sql
  tests/cypress/cypress/integration/publish/field_short_names.electron.js
  tests/cypress/electron.cypress.config.js
  tests/cypress/support/config/config.php
  themes/ee/asset/javascript/src/common.js
  themes/ee/cp/css/common.min.css
Labels: enhancement, test covered

#3470 Improved getting real IP address of visitor when using load balancers
  composer.json
  composer.lock
  system/ee/ExpressionEngine/Config/proxy.php
  system/ee/legacy/core/Input.php
  vendor-bin/php-scoper/composer.lock
Labels: Bug: Accepted, docs covered

#3424 Added ability to edit file metadata from file field
  system/ee/ExpressionEngine/Addons/file/ft.file.php
  system/ee/ExpressionEngine/Addons/file/views/publish.php
  system/ee/ExpressionEngine/Controller/Files/AbstractFiles.php
  system/ee/ExpressionEngine/Controller/Files/File.php
  system/ee/ExpressionEngine/View/files/edit.php
  system/ee/language/english/fieldtypes_lang.php
  tests/cypress/cypress/integration/publish/publish.ee6.js
  themes/ee/asset/javascript/src/cp/modal_form.js
  themes/ee/asset/javascript/src/fields/file/control_panel.js
Labels: enhancement, test covered, docs covered, MAJOR

#3355 Resolved #2806 where relationships field data was not saved if that was the only change for ChannelEntry model
  system/ee/ExpressionEngine/Addons/relationship/ft.relationship.php
  system/ee/ExpressionEngine/Library/Data/Entity.php
Labels: Bug: Accepted

#3868 Resolved #3865 where cloning entries with field groups in Fluid field did not retain grouping
  system/ee/ExpressionEngine/Addons/fluid_field/ft.fluid_field.php
Labels: Bug: Accepted

#3268 Do not join on field data tables, if no custom fields exist on model
  system/ee/ExpressionEngine/Library/Data/Entity.php
  system/ee/ExpressionEngine/Model/Category/Gateway/CategoryFieldDataGateway.php
  system/ee/ExpressionEngine/Model/Channel/Gateway/ChannelDataGateway.php
  system/ee/ExpressionEngine/Model/File/Gateway/FileFieldDataGateway.php
  system/ee/ExpressionEngine/Model/Member/Gateway/MemberFieldDataGateway.php
  system/ee/ExpressionEngine/Service/Model/Gateway.php
  system/ee/ExpressionEngine/Service/Model/MetaDataReader.php
  system/ee/ExpressionEngine/Service/Model/Query/Builder.php
Labels: performance, MAJOR

#3775 Improved styling of Slider fieldtypes when used with Channel Form
  system/ee/ExpressionEngine/Addons/slider/View/pair.php
  system/ee/ExpressionEngine/Addons/slider/View/single.php
  system/ee/ExpressionEngine/Addons/slider/ft.range_slider.php
  system/ee/ExpressionEngine/Addons/slider/ft.slider.php
  themes/ee/cform/css/eecms-cform.min.css
Labels: enhancement

#2817 Resolved #2703 where legacy member template could be shown when placing empty member tag; Enabled `{exp:member:has_role}` to check against multiple roles; #2749
  system/ee/ExpressionEngine/Addons/member/mod.member.php
  system/ee/ExpressionEngine/Addons/member/mod.member_images.php
  system/ee/ExpressionEngine/Addons/member/mod.member_memberlist.php
  system/ee/ExpressionEngine/Addons/member/mod.member_register.php
  system/ee/ExpressionEngine/Addons/member/mod.member_settings.php
  tests/cypress/cypress/integration/members/member_tags.ee6.js
  tests/cypress/support/templates/default_site/mbr.group/has_role.html
Labels: enhancement, test covered, docs covered

#3410 Ensure built-in roles are always present; #3200
  system/ee/installer/controllers/wizard.php
  system/ee/installer/schema/mysql_schema.php
  system/ee/installer/updates/ud_7_04_00.php
Labels: enhancement

#3845 Introduced additional permissions to manage category groups; #3831
  system/ee/ExpressionEngine/Controller/Categories/AbstractCategories.php
  system/ee/ExpressionEngine/Controller/Categories/Categories.php
  system/ee/ExpressionEngine/Controller/Categories/Groups.php
  system/ee/ExpressionEngine/Controller/Members/Roles/Roles.php
  system/ee/installer/schema/mysql_schema.php
  system/ee/installer/updates/ud_7_04_00.php
  system/ee/language/english/members_lang.php
  system/ee/legacy/libraries/Core.php
  tests/cypress/cypress/integration/content/global_variables.ee6.js
  tests/cypress/cypress/integration/member_roles/member_roles_channel.ee6.js
  tests/cypress/cypress/integration/publish/publish.ee6.js
Labels: enhancement, docs covered

#3777 Improved styles for Grid fieldtype in Channel Form
  themes/ee/cform/css/eecms-cform.min.css
Labels: enhancement

#3779 Improved styles for Date fieldtype in Channel Form
  themes/ee/cform/css/eecms-cform.min.css
Labels: enhancement

#3778 Improved styling of Selectable Buttons fieldtype when used with Channel Form
  system/ee/ExpressionEngine/Addons/selectable_buttons/ft.selectable_buttons.php
  themes/ee/asset/javascript/src/fields/buttons/button.js
  themes/ee/cform/css/eecms-cform.min.css
Labels: enhancement

#3460 Resolved #243 where email length was limited to maximum username length
  system/ee/ExpressionEngine/Addons/member/mod.member.php
  system/ee/ExpressionEngine/Controller/Members/Members.php
  system/ee/ExpressionEngine/Controller/Members/Profile/Email.php
  system/ee/ExpressionEngine/Controller/Utilities/MemberImport.php
  system/ee/ExpressionEngine/Model/Member/Member.php
  system/ee/installer/controllers/wizard.php
  system/ee/installer/schema/mysql_schema.php
  system/ee/installer/updates/ud_7_04_00.php
  tests/cypress/cypress/integration/members/member_create.ee6.js
Labels: Bug: Accepted, test covered, docs covered

#3031 Added Members fieldtype to select one or multiple members in channel entry; #1080
  system/ee/ExpressionEngine/Addons/channel/mod.channel.php
  system/ee/ExpressionEngine/Addons/member/addon.setup.php
  system/ee/ExpressionEngine/Addons/member/ft.member.php
  system/ee/ExpressionEngine/Addons/pro/Service/FrontEdit/FrontEdit.php
  system/ee/ExpressionEngine/Addons/relationship/ft.relationship.php
  system/ee/ExpressionEngine/Addons/relationship/views/publish.php
  system/ee/ExpressionEngine/Controller/Channels/AbstractChannels.php
  system/ee/ExpressionEngine/Controller/Members/Members.php
  system/ee/ExpressionEngine/Controller/Members/Profile/Auth.php
  system/ee/ExpressionEngine/Controller/Members/Profile/Email.php
  system/ee/ExpressionEngine/Controller/Members/Profile/Profile.php
  system/ee/ExpressionEngine/Controller/Members/Profile/Roles.php
  system/ee/ExpressionEngine/Controller/Members/Profile/Settings.php
  system/ee/ExpressionEngine/Controller/Publish/Publish.php
  system/ee/ExpressionEngine/Model/Channel/ChannelEntry.php
  system/ee/ExpressionEngine/Model/Member/Member.php
  system/ee/ExpressionEngine/Tests/ExpressionEngine/Controllers/Publish/PublishTest.php
  system/ee/ExpressionEngine/View/_shared/iframe-modal.php
  system/ee/ExpressionEngine/View/settings/modal-form.php
  system/ee/installer/schema/mysql_schema.php
  system/ee/installer/updates/ud_7_04_00.php
  system/ee/language/english/content_lang.php
  system/ee/language/english/fieldtypes_lang.php
  system/ee/legacy/libraries/api/Api_channel_fields.php
  system/ee/legacy/libraries/channel_entries_parser/components/Custom_field.php
  system/ee/legacy/libraries/channel_entries_parser/components/Custom_member_field.php
  system/ee/legacy/libraries/channel_entries_parser/components/Simple_variable.php
  tests/cypress/cypress/integration/publish/member_field.ee6.js
  tests/cypress/support/sql/grid-and-fluid.sql
  tests/cypress/support/templates/default_site/entries.group/members.html
  themes/ee/asset/javascript/src/cp/modal_form.js
  themes/ee/cp/js/build/components/relationship.js
  themes/ee/cp/js/src/components/relationship.jsx
Labels: enhancement, test covered, MAJOR

#3072 Improved Entry Date field to make it user-friendly to pick a different time, #3021
  cp-styles/app/styles/legacy/_date-picker.scss
  system/ee/ExpressionEngine/Addons/date/ft.date.php
  system/ee/ExpressionEngine/Addons/date/views/publish.php
  system/ee/ExpressionEngine/Library/Date/DateTrait.php
  system/ee/ExpressionEngine/Service/Filter/Date.php
  system/ee/language/english/calendar_lang.php
  tests/cypress/cypress/elements/pages/channel/ChannelFieldForm.js
  tests/cypress/cypress/integration/publish/publish.ee6.js
  themes/ee/asset/javascript/src/cp/date_picker.js
  themes/ee/cp/css/common.min.css
Labels: enhancement, test covered, docs covered

#3702 Added {exp:member:role_groups} template tag
  system/ee/ExpressionEngine/Addons/member/mod.member.php
Labels: enhancement, docs covered

#3409 Added `cli_boot` and `cli_before_handle` extension hook to run on each CLI request; #2846
  system/ee/ExpressionEngine/Cli/Cli.php
  system/ee/ExpressionEngine/Service/Generator/Enums/Hooks.php
  system/ee/installer/updates/ud_7_04_00.php
Labels: development, docs covered

#3862 Resolved #3841 where some characters in entry title might cause automatic url_title generation to not work
  system/ee/ExpressionEngine/Service/Formatter/Formats/Text.php
  system/ee/ExpressionEngine/Tests/ExpressionEngine/Service/Formatter/TextFormatterTest.php
Labels: Bug: Accepted

#3555 Allow making category group required for channel; Allow restricting category selection to single category per group
  cp-styles/app/styles/components/_checkboxes-and-radios.scss
  system/ee/ExpressionEngine/Addons/channel/libraries/channel_form/Channel_form_lib.php
  system/ee/ExpressionEngine/Addons/channel/mod.channel.php
  system/ee/ExpressionEngine/Addons/checkboxes/ft.checkboxes.php
  system/ee/ExpressionEngine/Addons/metaweblog_api/mod.metaweblog_api.php
  system/ee/ExpressionEngine/Addons/moblog/mcp.moblog.php
  system/ee/ExpressionEngine/Addons/moblog/mod.moblog.php
  system/ee/ExpressionEngine/Addons/pro_search/mcp.pro_search.php
  system/ee/ExpressionEngine/Addons/radio/ft.radio.php
  system/ee/ExpressionEngine/Controller/Categories/Categories.php
  system/ee/ExpressionEngine/Controller/Categories/Groups.php
  system/ee/ExpressionEngine/Controller/Channels/Channels.php
  system/ee/ExpressionEngine/Controller/Files/Uploads.php
  system/ee/ExpressionEngine/Controller/Publish/AbstractPublish.php
  system/ee/ExpressionEngine/Controller/Publish/BulkEdit/AbstractBulkEdit.php
  system/ee/ExpressionEngine/Library/CP/FileManager/Traits/FileManagerTrait.php
  system/ee/ExpressionEngine/Model/Category/CategoryGroup.php
  system/ee/ExpressionEngine/Model/Category/CategoryGroupSettings.php
  system/ee/ExpressionEngine/Model/Channel/Channel.php
  system/ee/ExpressionEngine/Model/Channel/ChannelEntry.php
  system/ee/ExpressionEngine/Model/Channel/Display/DefaultChannelLayout.php
  system/ee/ExpressionEngine/Model/Content/Display/FieldDisplay.php
  system/ee/ExpressionEngine/Model/Content/FieldFacade.php
  system/ee/ExpressionEngine/Model/File/FileSystemEntity.php
  system/ee/ExpressionEngine/Model/File/UploadDestination.php
  system/ee/ExpressionEngine/Service/Category/Factory.php
  system/ee/ExpressionEngine/Service/EntryListing/EntryListing.php
  system/ee/ExpressionEngine/Service/File/Upload.php
  system/ee/ExpressionEngine/Service/Validation/Validator.php
  system/ee/ExpressionEngine/Service/View/ViewHelpers.php
  system/ee/ExpressionEngine/View/_shared/form/field.php
  system/ee/ExpressionEngine/View/_shared/form/fields/select.php
  system/ee/ExpressionEngine/View/publish/partials/publish_form.php
  system/ee/ExpressionEngine/app.setup.php
  system/ee/installer/schema/mysql_schema.php
  system/ee/installer/updates/ud_7_04_00.php
  system/ee/language/english/channel_lang.php
  system/ee/language/english/content_lang.php
  system/ee/legacy/libraries/Filemanager.php
  system/ee/legacy/libraries/api/Api_channel_entries.php
  tests/cypress/cypress/integration/channel/settings.ee6.js
  tests/cypress/cypress/integration/channel/status_create.ee6.js
  tests/cypress/cypress/integration/utilities/sql_manager.ee6.js
  tests/cypress/support/sql/database_7.0.0.sql
  themes/ee/asset/javascript/src/common.js
  themes/ee/asset/javascript/src/components/select_list.es6
  themes/ee/asset/javascript/src/components/select_list.js
  themes/ee/asset/javascript/src/fields/select/mutable_select.js
  themes/ee/asset/javascript/src/fields/select/select.es6
  themes/ee/asset/javascript/src/fields/select/select.js
  themes/ee/cp/css/common.min.css
Labels: enhancement, refactoring, test covered, docs covered, MAJOR

#3902 Added RedactorX as editing engine for RTE; Deprecated Redactor editing engine
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  .gitignore
  cp-styles/app/styles/components/_rte.scss
  cp-styles/app/styles/components/_select.scss
  system/ee/ExpressionEngine/Addons/rte/RteHelper.php
  system/ee/ExpressionEngine/Addons/rte/Service/RedactorService.php
  system/ee/ExpressionEngine/Addons/rte/Service/RedactorXService.php
  system/ee/ExpressionEngine/Addons/rte/addon.setup.php
  system/ee/ExpressionEngine/Addons/rte/ft.rte.php
  system/ee/ExpressionEngine/Addons/rte/javascript/rte.js
  system/ee/ExpressionEngine/Addons/rte/mcp.rte.php
  system/ee/ExpressionEngine/Addons/rte/mod.rte.php
  system/ee/ExpressionEngine/Addons/rte/upd.rte.php
  system/ee/ExpressionEngine/Addons/rte/views/redactorX-toolbar.php
  system/ee/language/english/rte_lang.php
  tests/cypress/cypress/integration/addons/addon_rte_settings.ee6.js
  themes/ee/asset/javascript/src/common.js
  themes/ee/asset/javascript/src/fields/dropdown/dropdown.es6
  themes/ee/asset/javascript/src/fields/dropdown/dropdown.js
  themes/ee/asset/javascript/src/fields/rte/rte.js
  themes/ee/cp/css/common.min.css
Labels: enhancement
