Repository ExpressionEngine/ExpressionEngine, pull requests merged in 2023-03, with the labels that each got.

#2849 Resolved an issue where the author filter could have a missing label.
  system/ee/ExpressionEngine/Service/EntryListing/EntryListing.php
Labels: Bug: Accepted

#3008 Resolved #2838 where the new related entry modal generates JS errors
  .github/workflows/tests-minimal.yml
  .github/workflows/tests.yml
  tests/cypress/cypress/integration/field/field_combinations.ee6.js
  themes/ee/cp/js/build/components/relationship.js
  themes/ee/cp/js/src/components/relationship.jsx
Labels: Bug: Accepted

#3009 Resolved #2829 where entry search in mobile view is not working
  cp-styles/app/styles/components/_filter-bar.scss
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#3022 Resolved issue where CKeditor table in vertical Grid didn't render correctly when creating a new entry
  cp-styles/app/styles/components/_grid-field.scss
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#3010 Resolved issue where PHP notice could be shown on Live Preview when invoked from Entries prolet
  system/ee/ExpressionEngine/Service/LivePreview/LivePreview.php
Labels: Bug: Accepted

#3014 Resolved issue where performing post-upgrade checks could show PHP error
  system/ee/ExpressionEngine/Model/Content/FieldFacade.php
Labels: Bug: Accepted

#2741 Resolved #2739 where PHP notice could have been shown when accessing plugin documentation when using PHP 8.1
  system/ee/ExpressionEngine/Controller/Addons/Addons.php
Labels: Bug: Accepted, EE6

#3040 Resolved #3028 where categories tab drag-and-drop re-ordering not working
  cp-styles/app/styles/components/_checkboxes-and-radios.scss
  themes/ee/asset/javascript/src/common.js
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#3054 Resolved #3048 where entry preview on mobile was broken
  cp-styles/app/styles/components/_live-preview.scss
  cp-styles/build/main.min.js
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#3050 Resolved #3035 where enabling front-end editing on very complex templates could cause some tags to be not parsed
  system/ee/legacy/libraries/api/Api_channel_fields.php
Labels: Bug: Accepted

#3032 Resolved #3030 where property in Channel module has wrong visibility
  system/ee/ExpressionEngine/Addons/channel/mod.channel.php
Labels: development

#3023 Resolved issue where CKeditor table in vertical Grid didn't render correctly when creating a new entry
  cp-styles/app/styles/components/_grid-field.scss
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#3037 Resolved issue where turning on front-end editing could cause some tags to not render correctly
  system/ee/ExpressionEngine/Addons/pro/Service/FrontEdit/FrontEdit.php
  tests/cypress/cypress/integration/pro/pro_backend.ee6.js
  tests/cypress/support/templates/default_site/pro.group/image.html
Labels: Bug: Accepted

#3039 Resolved #3028 where categories tab drag-and-drop re-ordering was not working
  cp-styles/app/styles/components/_checkboxes-and-radios.scss
  themes/ee/asset/javascript/src/common.js
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#3049 Resolved #3035 where enabling front-end editing on very complex templates could cause some tags to be not parsed
  system/ee/legacy/libraries/api/Api_channel_fields.php
Labels: Bug: Accepted

#3053 Resolved #3048 where entry preview on mobile was broken
  cp-styles/app/styles/components/_live-preview.scss
  cp-styles/build/main.min.js
  themes/ee/cp/css/common.min.css
  themes/ee/debug/css/eecms-debug.min.css
Labels: Bug: Accepted

#2830 Account for dictionary words when calculating password rank; #1806
  .github/workflows/unit-tests.yml
  system/ee/ExpressionEngine/Service/Member/Member.php
Labels: enhancement

#3060 Resolved #2775 where approved members could have Pending as secondary role
  system/ee/ExpressionEngine/Controller/Members/Members.php
Labels: Bug: Accepted

#3059 Resolved #2775 where approved members could have Pending as secondary role
  system/ee/ExpressionEngine/Controller/Members/Members.php
Labels: Bug: Accepted

#3097 Resolved #3093 where deprecation message could be shown when editing member using PHP 8.1
  system/ee/ExpressionEngine/Service/Member/Member.php
Labels: Bug: Accepted

#3088 Resolved #2207 where the bug report link was incorrect
  build-tools/build.json
  system/ee/ExpressionEngine/Tests/bootstrap.php
  system/ee/ExpressionEngine/View/_shared/footer.php
  system/ee/installer/controllers/wizard.php
  system/ee/installer/updates/ud_7_02_12.php
  system/ee/legacy/libraries/Core.php
  tests/cypress/support/config/config.php
Labels: Bug: Accepted

#3083 Resolved #2842 where channel form with HTML buttons could show notices when using PHP 8.1
  system/ee/ExpressionEngine/Addons/channel/libraries/channel_form/Channel_form_lib.php
Labels: Bug: Accepted

#3081 Resolved #3069 where `ChannelField` model could not be saved without `field_order` property
  system/ee/ExpressionEngine/Model/Channel/ChannelField.php
Labels: development

#3079 Resolved #3075 where some email notifications did not respect HTML formatting preference
  system/ee/ExpressionEngine/Addons/comment/Service/Notifications.php
  system/ee/ExpressionEngine/Addons/member/mod.member_register.php
  system/ee/legacy/controllers/cp/login.php
Labels: Bug: Accepted

#3074 Resolved #2839 where manipulation URL was wrong for SVG files
  system/ee/legacy/libraries/File_field.php
Labels: Bug: Accepted

#3096 Resolved #3093 where deprecation message could be shown when editing member using PHP 8.1
  system/ee/ExpressionEngine/Service/Member/Member.php
Labels: Bug: Accepted

#3084 Resolved #2842 where channel form with HTML buttons could show notices when using PHP 8.1
  system/ee/ExpressionEngine/Addons/channel/libraries/channel_form/Channel_form_lib.php
Labels: Bug: Accepted

#3082 Resolved #3069 where `ChannelField` model could not be saved without `field_order` property
  system/ee/ExpressionEngine/Model/Channel/ChannelField.php
Labels: development

#3080 Resolved #3075 where some email notifications did not respect HTML formatting preference
  .gitignore
  system/ee/ExpressionEngine/Addons/comment/Service/Notifications.php
  system/ee/ExpressionEngine/Addons/member/mod.member_register.php
  system/ee/legacy/controllers/cp/login.php
Labels: Bug: Accepted
