Repository ExpressionEngine/ExpressionEngine, pull requests merged in 2024-03, with the labels that each got.

#4091 Resolved #4083 where <em> in RedaktorX is set to display:block
  cp-styles/app/styles/components/_rte.scss
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#4075 Resolved #4072 where Pro Search could show PHP deprecation error when using PHP 8.2
  system/ee/ExpressionEngine/Addons/pro_search/i18n/en/stemmer.php
Labels: Bug: Accepted

#4064 Resolved issue where `:excerpt` modifier on RTE field could cause PHP notice
  system/ee/ExpressionEngine/Addons/rte/ft.rte.php
Labels: Bug: Accepted

#4035 Resolved #4033 where Menu Sets item could not have been moved to the bottom
  system/ee/language/english/settings_lang.php
  themes/ee/asset/javascript/src/components/select_list.es6
  themes/ee/asset/javascript/src/components/select_list.js
Labels: Bug: Accepted

#3996 Resolved #3910 where Javascript to encode / decode email addresses uses deprecated 'unescape' function
  system/ee/legacy/helpers/url_helper.php
  system/ee/legacy/libraries/Typography.php
Labels: development

#3917 Improved styles for Entry Status dropdown on Publish pages
  cp-styles/app/styles/legacy/_status-tag.scss
  themes/ee/cp/css/common.min.css
Labels: enhancement

#3976 Resolved #3645 where Autosave did not include data from Grids with Relationships
  themes/ee/asset/javascript/src/cp/publish/publish.js
  themes/ee/asset/javascript/src/fields/dropdown/dropdown.es6
  themes/ee/asset/javascript/src/fields/dropdown/dropdown.js
  themes/ee/asset/javascript/src/fields/file/control_panel.js
  themes/ee/asset/javascript/src/fields/file/drag_and_drop_upload.es6
  themes/ee/asset/javascript/src/fields/file/drag_and_drop_upload.js
  themes/ee/cp/js/build/components/colorpicker.js
  themes/ee/cp/js/build/components/relationship.js
  themes/ee/cp/js/src/components/colorpicker.tsx
  themes/ee/cp/js/src/components/relationship.jsx
Labels: Bug: Accepted

#4029 Added fallback for PHP `tmpfile()` function when it's not enabled
  system/ee/ExpressionEngine/Boot/boot.common.php
  system/ee/ExpressionEngine/Library/Filesystem/TempFileFactory.php
Labels: enhancement: accepted

#4047 Resolved #4040 where required column indicators were missing inside Grid field
  cp-styles/app/styles/components/_grid-field.scss
  system/ee/ExpressionEngine/View/_shared/table.php
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#4107 Resolved #4102 where template layouts could skip some variables
  system/ee/legacy/libraries/Template.php
Labels: Bug: Accepted

#4121 Resolved #4116 where PHP warning could be shown when using template layouts
  system/ee/legacy/libraries/Template.php
Labels: Bug: Accepted

#4080 Resolved #4079 where orphan relationship record could cause PHP notices
  system/ee/legacy/libraries/relationship_parser/Parser.php
Labels: Bug: Accepted

#4082 Resolved #4077 where PHP deprecation notice could have been shown for some migrated Pro Variables
  system/ee/ExpressionEngine/Addons/pro_variables/types/type.pro_variables.php
Labels: Bug: Accepted

#4090 Changed property visibility
  system/ee/legacy/core/Controller.php
Labels: refactoring

#3954 Enable setting global variables in config file; #3015
  system/ee/legacy/core/Config.php
Labels: enhancement

#3922 Resolved #987 where pagination could be wrong on Entry Manager if Categories column present
  system/ee/ExpressionEngine/Library/CP/EntryManager/Columns/Categories.php
Labels: Bug: Accepted

#4118 Resolved issue where Enum validation was not working when using PHP8+
  system/ee/ExpressionEngine/Service/Validation/Rule/Enum.php
  system/ee/ExpressionEngine/Service/Validation/Rule/LimitHtml.php
Labels: Bug: Accepted

#4132 Resolved #4111 where reordering groups did not work in Pro Variables
  system/ee/ExpressionEngine/Addons/pro_variables/javascript/pro_variables.js
Labels: Bug: Accepted

#4138 Resolved issue where certain uses of Member model in CLI requests were causing errors
  system/ee/ExpressionEngine/Model/Member/Member.php
Labels: Bug: Accepted

#4133 Changed default limit in Members field settings
  system/ee/ExpressionEngine/Addons/member/ft.member.php
Labels: enhancement

#4140 Resolved issue where saving RTE toolset could show an error
  system/ee/ExpressionEngine/Addons/rte/mcp.rte.php
Labels: Bug: Accepted

#4144 Resolved #4129 where CSRF token not getting refreshed when CP session type is "session only"
  themes/ee/asset/javascript/src/cp/global_start.js
Labels: Bug: Accepted

#4150 Resolved #4147 where label of dropdown select field for member was not parsed correctly
  system/ee/legacy/libraries/api/Api_channel_fields.php
Labels: Bug: Accepted

#4097 Resolved #3972 where it was not possible to use 1-click Updater on servers with `disk_free_space()` disabled
  system/ee/ExpressionEngine/Library/Filesystem/Filesystem.php
  system/ee/ExpressionEngine/Service/Database/Backup/Backup.php
  system/ee/ExpressionEngine/Service/Updater/Downloader/Preflight.php
  system/ee/ExpressionEngine/Tests/ExpressionEngine/Service/Updater/Downloader/PreflightTest.php
  system/ee/installer/updater/ExpressionEngine/Updater/Library/Filesystem/Filesystem.php
Labels: enhancement: accepted

#4137 Resolved #4135 where removing page with children from Structure was giving an error
  system/ee/ExpressionEngine/Addons/structure/mod.structure.php
Labels: Bug: Accepted

#4126 Enabled testing of email configuration from email settings page
  system/ee/ExpressionEngine/Controller/Settings/Email.php
  system/ee/ExpressionEngine/View/settings/email-verify.php
  system/ee/language/english/settings_lang.php
  system/ee/legacy/libraries/Email.php
  themes/ee/asset/javascript/src/cp/modal_form.js
  themes/ee/asset/javascript/src/cp/settings/email.js
Labels: enhancement

#4078 Modified the addon update process to stay on Updates tab if more updates are available; #2860
  system/ee/ExpressionEngine/Controller/Addons/Addons.php
  system/ee/ExpressionEngine/View/addons/index.php
Labels: enhancement, UX

#3944 Added Debug Channel Entries Utility; #3024
  system/ee/ExpressionEngine/Controller/Utilities/DebugTools.php
  system/ee/ExpressionEngine/Controller/Utilities/Utilities.php
  system/ee/ExpressionEngine/Library/Advisor/EntryAdvisor.php
  system/ee/ExpressionEngine/Service/JumpMenu/JumpMenu.php
  system/ee/ExpressionEngine/View/utilities/debug-tools/channel_entries.php
  system/ee/ExpressionEngine/View/utilities/debug-tools/index.php
  system/ee/ExpressionEngine/View/utilities/debug-tools/missing_fieldtypes.php
  system/ee/language/english/utilities_lang.php
Labels: enhancement

#3729 Enable on-the-fly cropping from image center; #2947
  system/ee/ExpressionEngine/Addons/file/ft.file.php
Labels: enhancement

#4176 Resolved #4165 where Pro Variables prolet was showing PHP warning if single variables were used
  system/ee/ExpressionEngine/Addons/pro_variables/mod.pro_variables.php
Labels: Bug: Accepted

#3800 Added `{index}` and `{total_items}` variables to options fieldtypes; #3363
  system/ee/legacy/fieldtypes/OptionFieldtype.php
  tests/cypress/cypress/integration/content/checkboxes.ee6.js
  tests/cypress/support/templates/default_site/entries.group/checkboxes.html
Labels: enhancement, test covered, docs covered

#4154 Resolved #4098 where Date field by default was not setting time to current
  themes/ee/asset/javascript/src/cp/date_picker.js
Labels: enhancement: accepted

#4184 Resolved issue where template conditionals could show PHP warning
  system/ee/ExpressionEngine/Library/Parser/Conditional/BooleanExpression.php
Labels: Bug: Accepted

#3924 Default search in Entry Manager to "Titles only"; #3431
  system/ee/ExpressionEngine/Controller/Publish/Edit.php
Labels: enhancement

#3960 Resolved #3959 where sort order of categories in Entry Manager filter could have been wrong
  system/ee/ExpressionEngine/Service/EntryListing/EntryListing.php
  system/ee/ExpressionEngine/Service/Filter/Filter.php
  system/ee/ExpressionEngine/View/_shared/filters/filter.php
Labels: Bug: Accepted

#4070 Resolved #4045 where Relationship field did not fully respect "sort by date" setting
  system/ee/ExpressionEngine/Addons/relationship/libraries/EntryList.php
Labels: Bug: Accepted

#3953 Resolved #3950 where order of upload directories and folders was not consistent in dropdowns
  system/ee/ExpressionEngine/Library/CP/FileManager/Traits/FileManagerTrait.php
  system/ee/ExpressionEngine/Model/File/UploadDestination.php
  system/ee/legacy/libraries/File_field.php
Labels: Bug: Accepted

#4114 Resolved issue when using out-of-date translation files could cause language keys to show instead of messages
  system/ee/legacy/core/Lang.php
Labels: Bug: Accepted

#4161 Fix PHP warnings from string functions
  system/ee/legacy/core/Input.php
  system/ee/legacy/libraries/Typography.php
Labels: Bug: Accepted

#4181 Improved Avatar image to ensure it correctly displays images of all aspect ratios; #4175
  cp-styles/app/styles/components/_main-header.scss
  themes/ee/cp/css/common.min.css
Labels: enhancement

#4158 Fixed #4152 where eecms-cform overriding styles
  themes/ee/cform/css/eecms-cform.min.css
Labels: enhancement

#4182 Resolved #4180 where some regular expression patterns could not be used for validation
  system/ee/ExpressionEngine/Service/Validation/Validator.php
Labels: Bug: Accepted

#4174 Resolved issue where language was not fully loaded for date picker in channel form
  system/ee/ExpressionEngine/Addons/channel/libraries/channel_form/Channel_form_lib.php
Labels: Bug: Accepted
