Repository ExpressionEngine/ExpressionEngine, pull requests merged in 2024-12, with the labels that each got.

#4526 Resolved #4525 where selecting specific date in filter shows error when paginating
  system/ee/ExpressionEngine/Service/Filter/Date.php
  system/ee/ExpressionEngine/Service/Filter/Filter.php
Labels: Bug: Accepted

#4580 Fix issue where entry titles with certain characters did not display correctly
  system/ee/ExpressionEngine/Addons/pro/View/widgets/recent_entries.php
  system/ee/ExpressionEngine/Controller/Channels/Channels.php
  system/ee/ExpressionEngine/Controller/Fields/Fields.php
  system/ee/ExpressionEngine/Model/Channel/ChannelEntry.php
  system/ee/ExpressionEngine/Model/File/File.php
Labels: Bug: Accepted

#4611 Improve member tag support for multiple template engines
  system/ee/ExpressionEngine/Addons/channel/libraries/channel_form/Channel_form_lib.php
  system/ee/ExpressionEngine/Addons/member/mod.member.php
  system/ee/ExpressionEngine/Addons/member/mod.member_images.php
  system/ee/ExpressionEngine/Addons/member/mod.member_memberlist.php
  system/ee/ExpressionEngine/Addons/member/mod.member_register.php
  system/ee/ExpressionEngine/Addons/member/mod.member_settings.php
  system/ee/legacy/libraries/Pagination.php
Labels: enhancement

#4612 Resolved an issue where the tmpfile fallback is called
  system/ee/ExpressionEngine/Library/Filesystem/TempFileFactory.php
Labels: Bug: Accepted

#4613 Resolved #4564 where deprecated `utf8_decode` function was used
  system/ee/ExpressionEngine/Service/Formatter/Formats/Text.php
Labels: Bug: Accepted

#4614 Resolved #4544 where frontend editing did not work if field was moved to different layout tab
  system/ee/ExpressionEngine/Controller/Publish/Edit.php
Labels: Bug: Accepted

#4616 Show icon in template manager if caching is enabled; #4578
  system/ee/ExpressionEngine/Controller/Design/AbstractDesign.php
Labels: enhancement, Bug: Accepted

#4618 Resolved #4617 where applying transformation to non-existing image would prevent a page from displaying
  system/ee/ExpressionEngine/Addons/file/ft.file.php
  system/ee/ExpressionEngine/Library/Filesystem/Filesystem.php
Labels: Bug: Accepted

#4619 Set correct HTTP header when accessing invalid action URLs; #4571
  system/ee/legacy/libraries/Actions.php
Labels: enhancement, Bug: Accepted

#4620 Added dd.mm.yyyy date format; #4540
  system/ee/legacy/core/Config.php
Labels: enhancement

#4621 Resolved an issue where the default template engine was not used when copying field codes
  system/ee/ExpressionEngine/Controller/Design/Copy.php
  system/ee/ExpressionEngine/Service/View/Stub.php
Labels: Bug: Accepted

#4602 Resolved issue where not correct error was shown when installing EE for the first time and not having config file
  system/ee/legacy/core/Exceptions.php
Labels: Bug: Accepted
