Repository ExpressionEngine/ExpressionEngine, pull requests merged in 2024-06, with the labels that each got.

#4293 Resolved #4286 and #4287 where member listings had pagination issues
  system/ee/ExpressionEngine/Controller/Members/Members.php
Labels: Bug: Accepted

#4357 Resolve a serialization issue where retrieving a field from cache might not setup its fieldtype properly
  system/ee/ExpressionEngine/Model/Category/CategoryField.php
  system/ee/ExpressionEngine/Model/Channel/ChannelField.php
Labels: Bug: Accepted

#3795 Added `{index}` and `{absolute_index}` variables to `{exp:channel:entries}` tag; #3768
  system/ee/legacy/libraries/channel_entries_parser/Parser.php
  tests/cypress/cypress/integration/content/entry_listing.ee6.js
  tests/cypress/support/templates/default_site/entries.group/index.html
Labels: enhancement, test covered, docs covered

#3809 Added `{exp:channel:field}` tag to display field properties; #2870
  system/ee/ExpressionEngine/Addons/channel/mod.channel.php
  tests/cypress/cypress/integration/field/channel_field_tag.ee6.js
  tests/cypress/support/templates/default_site/fields.group/properties.html
Labels: enhancement, test covered, docs covered

#3911 Resolved #3556 where date fields could not accommodate dates past year 2038
  build-tools/build.json
  system/ee/ExpressionEngine/Addons/date/ft.date.php
  system/ee/ExpressionEngine/Tests/bootstrap.php
  system/ee/installer/controllers/wizard.php
  system/ee/installer/schema/mysql_schema.php
  system/ee/installer/updates/ud_7_05_00.php
  system/ee/legacy/libraries/Core.php
  tests/cypress/support/config/config.php
Labels: Bug: Accepted

#4222 Enable cloning of Menu Sets; #4214
  system/ee/ExpressionEngine/Controller/Settings/MenuManager.php
  system/ee/language/english/settings_lang.php
Labels: enhancement

#4030 Fluid Field Group Improvements
  images/about/index.html
  images/uploads/index.html
  system/ee/ExpressionEngine/Addons/fluid_field/Service/Tag.php
  system/ee/ExpressionEngine/Addons/fluid_field/ft.fluid_field.php
  system/ee/legacy/libraries/Fluid_field_parser.php
  tests/cypress/cypress/integration/publish/fluid.ee6.js
  tests/cypress/cypress/integration/publish/publish.ee6.js
  tests/cypress/support/templates/default_site/entries.group/fluid-group.html
Labels: enhancement

#4109 Update the message templates to current ones, if the site is using EE2 versions of those
  system/ee/installer/updates/ud_7_05_00.php
  system/ee/legacy/libraries/Core.php
Labels: enhancement
