Repository ExpressionEngine/ExpressionEngine, pull requests merged in 2024-04, with the labels that each got.

#3977 Resolved #3645 where Autosave does not include data from Grids with Relationships
  themes/ee/asset/javascript/src/cp/publish/publish.js
  themes/ee/asset/javascript/src/fields/dropdown/dropdown.es6
  themes/ee/asset/javascript/src/fields/dropdown/dropdown.js
  themes/ee/asset/javascript/src/fields/file/control_panel.js
  themes/ee/asset/javascript/src/fields/file/drag_and_drop_upload.es6
  themes/ee/asset/javascript/src/fields/file/drag_and_drop_upload.js
  themes/ee/cp/js/build/components/colorpicker.js
  themes/ee/cp/js/build/components/relationship.js
  themes/ee/cp/js/src/components/colorpicker.tsx
  themes/ee/cp/js/src/components/relationship.jsx
Labels: Bug: Accepted

#3990 Fix field_required warning in CP for Pro Variables/Grid with null
  system/ee/ExpressionEngine/Addons/grid/ft.grid.php
Labels: Bug: Accepted

#4092 Resolved #4068 where Branding upload disappears
  themes/ee/asset/javascript/src/fields/file/drag_and_drop_upload.es6
  themes/ee/asset/javascript/src/fields/file/drag_and_drop_upload.js
Labels: Bug: Accepted

#4119 Resolved issue where Enum validation was not working when using PHP8+
  system/ee/ExpressionEngine/Service/Validation/Rule/Enum.php
  system/ee/ExpressionEngine/Service/Validation/Rule/LimitHtml.php
Labels: Bug: Accepted

#4139 Resolved issue where certain uses of Member model in CLI requests were causing errors
  system/ee/ExpressionEngine/Model/Member/Member.php
Labels: Bug: Accepted

#4153 Resolved #4148 where SuperAdmins were not able to approve members into Locked roles
  system/ee/ExpressionEngine/Controller/Members/Members.php
  tests/cypress/cypress/integration/members/register.ee6.js
  tests/cypress/support/sql/more-roles.sql
Labels: Bug: Accepted

#4206 Resolved #3654 where incorrect fieldtype options were shown on load
  system/ee/ExpressionEngine/Controller/Fields/Fields.php
Labels: Bug: Accepted

#4183 Improved Authors dropdown when editing entry by showing Member ID; #4168
  themes/ee/asset/javascript/src/components/select_list.es6
  themes/ee/asset/javascript/src/components/select_list.js
Labels: enhancement

#4198 Resolved #4194 where profile edit form needed extra validation
  system/ee/ExpressionEngine/Addons/member/mod.member_settings.php
  tests/cypress/cypress/integration/members/profile.ee6.js
Labels: Bug: Accepted

#4200 Resolved #4193 where Select dropdown could show incorrect values as selected
  themes/ee/asset/javascript/src/components/select_list.es6
  themes/ee/asset/javascript/src/components/select_list.js
  themes/ee/asset/javascript/src/fields/dropdown/dropdown.es6
  themes/ee/asset/javascript/src/fields/dropdown/dropdown.js
Labels: Bug: Accepted

#3801 Do not hide saved field options in entry if the field settings do not contain those options anymore; #2973
  system/ee/legacy/fieldtypes/EE_Fieldtype.php
  tests/cypress/cypress/integration/field/field_settings.ee6.js
Labels: Bug: Accepted, test covered

#4202 Resolved #4069 where incorrect fieldtype options were shown on load
  system/ee/ExpressionEngine/Controller/Fields/Fields.php
Labels: Bug: Accepted

#4218 Resolved #4210 where members fieldtype had issues in LivePreview
  system/ee/ExpressionEngine/Addons/member/ft.member.php
  system/ee/ExpressionEngine/Service/LivePreview/LivePreview.php
  system/ee/legacy/libraries/channel_entries_parser/components/Custom_field.php
  themes/ee/cp/js/build/components/relationship.js
  themes/ee/cp/js/src/components/relationship.jsx
Labels: Bug: Accepted

#4221 Fixed an issue where reordering items in Menu Sets did not work
  themes/ee/asset/javascript/src/common.js
Labels: Bug: Accepted

#4203 Adding target="_blank" to field info
  system/ee/language/english/fieldtypes_lang.php
Labels: enhancement: accepted

#4046 Resolved #3992 where Superadmin did not have a way to disable MFA for users
  system/ee/ExpressionEngine/Addons/pro/Controller/Members/Profile/Mfa.php
  system/ee/ExpressionEngine/Controller/Members/Profile/Profile.php
  system/ee/language/english/pro_lang.php
Labels: Bug: Accepted

#4199 Resolved #4192 where edit_avatar tag did not accept webp file
  system/ee/ExpressionEngine/Addons/member/mod.member_images.php
  system/ee/legacy/libraries/Members.php
Labels: Bug: Accepted

#3934 Allow automatic login after account activation; Allow redirect to custom page after account activation; #3581
  system/ee/ExpressionEngine/Addons/member/mod.member_register.php
  system/ee/ExpressionEngine/Controller/Settings/Members.php
  system/ee/ExpressionEngine/Service/JumpMenu/JumpMenu.php
  system/ee/installer/controllers/wizard.php
  system/ee/language/english/settings_lang.php
  system/ee/legacy/core/Config.php
  tests/cypress/cypress/integration/members/register.ee6.js
  tests/cypress/package-lock.json
  tests/cypress/package.json
Labels: enhancement, needs documentation

#3983 Resolved #3951 where File Grid doesn't allow uploading multiple images using "Upload New" button
  system/ee/ExpressionEngine/Addons/file/views/publish.php
  system/ee/ExpressionEngine/Addons/grid/views/file_grid.php
  system/ee/ExpressionEngine/Library/CP/FileManager/Traits/FileManagerTrait.php
  themes/ee/asset/javascript/src/fields/file/drag_and_drop_upload.es6
  themes/ee/asset/javascript/src/fields/file/drag_and_drop_upload.js
  themes/ee/cp/js/build/components/dropdown_button.js
  themes/ee/cp/js/src/components/dropdown_button.jsx
Labels: Bug: Accepted

#4237 Resolved #1333 where having template files stored outside of site folder could cause PHP warnings
  system/ee/ExpressionEngine/Model/Template/TemplateGroup.php
Labels: Bug: Accepted

#4253 Resolved issue where an entry without structure parent fails validation
  system/ee/ExpressionEngine/Addons/structure/tab.structure.php
  system/ee/legacy/fieldtypes/EE_Fieldtype.php
Labels: Bug: Accepted

#4205 Resolved #4187 where Pro Variables tag was causing a warning
  system/ee/ExpressionEngine/Service/Template/Variables/LegacyParser.php
Labels: Bug: Accepted

#4250 Added the focus on search input upon creating a new field type.
  cp-styles/app/styles/layout/_sidebar.scss
  themes/ee/cp/css/common.min.css
  themes/ee/cp/js/build/bootstrap/dropdown-controller.js
  themes/ee/cp/js/src/bootstrap/dropdown-controller.js
Labels: enhancement

#4257 Resolved #4246 where using `*` could result in invalid URL Title being generated programmatically
  system/ee/ExpressionEngine/Service/Formatter/Formats/Text.php
Labels: Bug: Accepted

#4259 Resolved #4207 where Color Picker settings were not displayed when adding new column into Grid field
  system/ee/ExpressionEngine/Addons/colorpicker/ft.colorpicker.php
  themes/ee/cp/js/build/bootstrap/dropdown-controller.js
Labels: Bug: Accepted

#4262 Resolved #4196 where Spam stopwords language file could not be loaded
  system/ee/legacy/core/Lang.php
Labels: Bug: Accepted

#4264 Resolved #4131 where not all custom fields were displayed when creating member in the CP
  system/ee/ExpressionEngine/Controller/Members/Members.php
Labels: Bug: Accepted

#4256 Fix structure empty template id validation issue
  system/ee/ExpressionEngine/Addons/structure/tab.structure.php
Labels: Bug: Accepted
