Repository ExpressionEngine/ExpressionEngine, pull requests merged in 2025-08, with the labels that each got.

#4527 Support PHP 8.4
  .github/workflows/phpcs.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  .github/workflows/tests-minimal.yml
  .github/workflows/tests.yml
  .github/workflows/unit-tests.yml
  README.md
  build-tools/README.md
  build-tools/composer.lock
  composer.json
  composer.lock
  scoper.inc.php
  system/ee/ExpressionEngine/Addons/fluid_field/Model/FluidField.php
  system/ee/ExpressionEngine/Addons/pro/Service/Mfa/Mfa.php
  system/ee/ExpressionEngine/Addons/structure/mod.structure.php
  system/ee/ExpressionEngine/Boot/boot.common.php
  system/ee/ExpressionEngine/Boot/boot.php
  system/ee/ExpressionEngine/Cli/Commands/CommandUpdate.php
  system/ee/ExpressionEngine/Controller/Fields/Fields.php
  system/ee/ExpressionEngine/Controller/Fields/Groups.php
  system/ee/ExpressionEngine/Controller/Members/Roles/Groups.php
  system/ee/ExpressionEngine/Controller/Members/Roles/Roles.php
  system/ee/ExpressionEngine/Controller/Settings/Consents.php
  system/ee/ExpressionEngine/Controller/Utilities/Communicate.php
  system/ee/ExpressionEngine/Core/Provider.php
  system/ee/ExpressionEngine/Library/CP/Form/Fields/Table.php
  system/ee/ExpressionEngine/Library/DataStructure/Tree/TreeFactory.php
  system/ee/ExpressionEngine/Model/Category/Category.php
  system/ee/ExpressionEngine/Model/Channel/ChannelEntry.php
  system/ee/ExpressionEngine/Model/Content/ContentModel.php
  system/ee/ExpressionEngine/Model/Member/Member.php
  system/ee/ExpressionEngine/Service/Event/Emitter.php
  system/ee/ExpressionEngine/Service/Filter/Columns.php
  system/ee/ExpressionEngine/Service/Filter/FileManagerColumns.php
  system/ee/ExpressionEngine/Service/Filter/MemberManagerColumns.php
  system/ee/ExpressionEngine/Service/Migration/Factory.php
  system/ee/ExpressionEngine/Service/Thumbnail/Thumbnail.php
  system/ee/ExpressionEngine/Service/Thumbnail/ThumbnailFactory.php
  system/ee/ExpressionEngine/Service/Validation/Result.php
  system/ee/ExpressionEngine/Tests/bootstrap.php
  system/ee/Mexitek/PHPColors/Color.php
  system/ee/installer/updater/ExpressionEngine/Tests/bootstrap.php
  system/ee/legacy/core/Exceptions.php
  system/ee/legacy/libraries/Encrypt.php
  system/ee/legacy/libraries/Template.php
  system/ee/legacy/libraries/Xmlrpc.php
  system/ee/legacy/libraries/Xmlrpcs.php
  system/ee/legacy/libraries/datastructures/Tree.php
  system/ee/legacy/libraries/simplepie/SimplePie/Parser.php
  tests/cypress/cypress/integration/member_roles/member_roles_website_access.ee6.js
  tests/cypress/cypress/support/commands.js
  tests/cypress/package-lock.json
  tests/cypress/package.json
  tests/cypress/support/sql/database_7.0.0.sql
  vendor-bin/php-scoper/composer.json
  vendor-bin/php-scoper/composer.lock
Labels: enhancement

#4438 Resolved #4430 where modules without `mcp` file did not update from CP
  system/ee/legacy/libraries/Addons.php
Labels: Bug: Accepted

#4905 Resolved #4886 where RTE field was not initialized in Member Fields
  themes/ee/asset/javascript/src/fields/rte/rte.js
Labels: Bug: Accepted

#4748 Improved precision when displaying file size in File Manager
  system/ee/ExpressionEngine/Library/CP/FileManager/Columns/Dimensions.php
  system/ee/ExpressionEngine/Library/CP/FileManager/Columns/FileSize.php
  system/ee/ExpressionEngine/Service/Formatter/Formats/Number.php
  system/ee/ExpressionEngine/Tests/ExpressionEngine/Service/Formatter/NumberFormatterTest.php
Labels: enhancement

#4747 Resolved #4708 where superadmins were not able to edit their own secondary roles
  system/ee/ExpressionEngine/Controller/Members/Profile/Profile.php
  system/ee/ExpressionEngine/Controller/Members/Profile/Roles.php
Labels: Bug: Accepted

#4940 Add mime_type parameter to {exp:file:entries} tag
  system/ee/ExpressionEngine/Addons/file/mod.file.php
Labels: enhancement: accepted

#4942 Fixed #4923 where RTE ckeditor unordered list style issue
  cp-styles/app/styles/components/_rte.scss
  themes/ee/cp/css/common.min.css
Labels: Bug: Accepted

#4869 Bypass on-the-fly manipulations if the image is not editable (e.g. SVG); #4868
  system/ee/ExpressionEngine/Addons/file/ft.file.php
Labels: enhancement

#4939 Resolved an issue where base_path and theme_path could be incorrectly set when installed with system folder above web root
  system/ee/installer/controllers/wizard.php
Labels: Bug: Accepted
